-- ===========================================================
-- Sprint D：服務履約、家屬資訊交接、異常處理與結算基礎
-- 在 Supabase SQL Editor 執行。可重複執行。
--
-- 服務主體（root）：care_bookings
--   本專案沒有 ServiceOrder / Assignment / ServiceTask 三層模型，
--   實際的正式服務關係就是 care_bookings（含 companion_id 與狀態流）。
--   本檔案所有資料表一律 FK 到 care_bookings，
--   刻意不另建平行的服務關係。
--
-- 與既有 care_booking_events 的分工（重要）：
--   care_booking_events  既有的陪診員工單時間軸，自由文字＋照片，
--                        仍由既有 /companion 工單頁使用，本檔案不修改它。
--   care_service_events  Sprint D 的「受控」事件：型別白名單、append-only、
--                        伺服器寫入時間、家屬可見性分層、更正留痕。
--   兩者 FK 到同一個 booking，不是兩套服務關係。
--   後續 Sprint 應把工單頁遷移到受控事件，屆時再淘汰舊表。
--
-- 這些表都不是醫療紀錄：不存診斷、處方、劑量、治療建議、病歷、
-- 影像、身分證／健保號或任何支付憑證。
-- ===========================================================

-- ── 1. 受控服務事件 ────────────────────────────────────────
create table if not exists care_service_events (
  id              bigint generated by default as identity primary key,
  booking_id      bigint not null references care_bookings(id) on delete restrict,
  companion_id    bigint references companions(id),

  event_type      text not null,
  -- 對家屬可見的簡短訊息，非醫療內容，長度受限
  family_note     text,
  -- internal：只有後台看得到；family：已允許對家屬顯示
  visibility      text not null default 'internal',

  -- 更正留痕：不刪除事件，改以 invalidated 標記並指向更正事件
  invalidated_at        timestamptz,
  invalidated_by_type   text,
  invalidate_reason_code text,
  supersedes_event_id   bigint references care_service_events(id),

  -- 事件時間一律由資料庫寫入，client 不得指定
  occurred_at     timestamptz not null default now(),
  created_at      timestamptz not null default now(),

  constraint care_evt_type_chk check (event_type in (
    'staff_arrived','beneficiary_met','registration_or_checkin_completed',
    'waiting_or_process_in_progress','process_transition',
    'return_arrangement_confirmed','service_handover_ready',
    'requires_supervisor_attention')),
  constraint care_evt_visibility_chk check (visibility in ('internal','family')),
  constraint care_evt_note_len_chk check (family_note is null or char_length(family_note) <= 120),
  constraint care_evt_invalidate_reason_chk check (
    invalidated_at is null or invalidate_reason_code is not null)
);
create index if not exists idx_care_evt_booking on care_service_events(booking_id, occurred_at desc);
create index if not exists idx_care_evt_companion on care_service_events(companion_id);
create index if not exists idx_care_evt_type on care_service_events(event_type);

-- append-only：已建立的事件不可刪除，也不可改寫內容
create or replace function care_guard_service_event() returns trigger
language plpgsql as $$
begin
  if TG_OP = 'DELETE' then
    raise exception 'care_service_events 為 append-only，不可刪除'
      using errcode = 'check_violation';
  end if;
  -- 只允許標記作廢，其餘欄位一律凍結
  if new.booking_id     is distinct from old.booking_id
     or new.companion_id is distinct from old.companion_id
     or new.event_type   is distinct from old.event_type
     or new.family_note  is distinct from old.family_note
     or new.occurred_at  is distinct from old.occurred_at
     or new.created_at   is distinct from old.created_at then
    raise exception 'care_service_events 為 append-only，只能標記作廢，不可改寫內容'
      using errcode = 'check_violation';
  end if;
  if old.invalidated_at is not null and new.invalidated_at is distinct from old.invalidated_at then
    raise exception '事件已作廢，不可重複作廢' using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_evt_guard on care_service_events;
create trigger trg_care_evt_guard before update or delete on care_service_events
  for each row execute function care_guard_service_event();

-- ── 2. 內部服務紀錄（陪診員草稿 → 送審 → 督導核對）────────
create table if not exists care_service_records (
  id                 bigint generated by default as identity primary key,
  booking_id         bigint not null references care_bookings(id) on delete restrict,
  companion_id       bigint not null references companions(id),
  revision           integer not null default 1,

  status             text not null default 'draft',

  -- 結構化的流程完成狀況（客觀事實，不是醫療內容）
  met_completed              boolean not null default false,
  checkin_completed          boolean not null default false,
  process_handover_completed boolean not null default false,
  return_arrangement_completed boolean not null default false,
  family_contact_completed   boolean not null default false,

  family_follow_up_needed    boolean not null default false,
  follow_up_reason_code      text,

  -- 客觀備註。欄位名稱刻意不用 note/diagnosis，避免暗示可寫醫療內容
  objective_summary  text,

  submitted_at       timestamptz,
  reviewed_at        timestamptz,
  reviewed_by_admin_id bigint,
  return_reason_code text,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint care_rec_status_chk check (status in
    ('draft','submitted','returned_for_revision','reviewed','superseded')),
  constraint care_rec_summary_len_chk check (
    objective_summary is null or char_length(objective_summary) <= 500),
  constraint care_rec_followup_chk check (
    family_follow_up_needed = false or follow_up_reason_code is not null),
  constraint care_rec_return_reason_chk check (
    status <> 'returned_for_revision' or return_reason_code is not null),
  constraint care_rec_revision_uniq unique (booking_id, revision)
);
create index if not exists idx_care_rec_booking on care_service_records(booking_id);
create index if not exists idx_care_rec_status on care_service_records(status);
create index if not exists idx_care_rec_companion on care_service_records(companion_id);

-- 一筆服務同時只能有一份「進行中」的紀錄
create unique index if not exists uniq_care_rec_active_per_booking
  on care_service_records(booking_id)
  where status in ('draft','submitted','returned_for_revision');

create or replace function care_guard_service_record() returns trigger
language plpgsql as $$
begin
  -- 已核可的紀錄內容不可被無聲改寫
  if old.status = 'reviewed' then
    if new.objective_summary is distinct from old.objective_summary
       or new.met_completed is distinct from old.met_completed
       or new.checkin_completed is distinct from old.checkin_completed
       or new.process_handover_completed is distinct from old.process_handover_completed
       or new.return_arrangement_completed is distinct from old.return_arrangement_completed
       or new.family_contact_completed is distinct from old.family_contact_completed
       or new.family_follow_up_needed is distinct from old.family_follow_up_needed then
      raise exception '已核可的服務紀錄不可修改內容，請建立新版本'
        using errcode = 'check_violation';
    end if;
  end if;

  -- 送審後陪診員不可再改內容（只有督導退回才能重新編輯）
  if old.status = 'submitted' and new.status = 'submitted' then
    if new.objective_summary is distinct from old.objective_summary then
      raise exception '已送審的服務紀錄不可修改，請先由督導退回'
        using errcode = 'check_violation';
    end if;
  end if;

  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'                 and new.status in ('submitted','superseded')) or
      (old.status = 'submitted'             and new.status in ('reviewed','returned_for_revision')) or
      (old.status = 'returned_for_revision' and new.status in ('submitted','superseded')) or
      (old.status = 'reviewed'              and new.status in ('superseded'))
    ) then
      raise exception 'care_service_record: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_rec_guard on care_service_records;
create trigger trg_care_rec_guard before update on care_service_records
  for each row execute function care_guard_service_record();

-- ── 3. 家屬小結（已審核、可發布／撤回、版本化）─────────────
create table if not exists care_family_summaries (
  id                 bigint generated by default as identity primary key,
  booking_id         bigint not null references care_bookings(id) on delete restrict,
  source_record_id   bigint references care_service_records(id),
  version_number     integer not null default 1,
  status             text not null default 'draft',

  -- 結構化的已發布內容；刻意不用單一自由文字塞整份小結
  service_window_text     text,
  completed_steps_text    text,
  family_actions_text     text,
  next_arrangement_text   text,
  handover_status_text    text,

  published_at       timestamptz,
  published_by_admin_id bigint,
  withdrawn_at       timestamptz,
  withdrawn_by_admin_id bigint,
  withdraw_reason_code text,

  created_by_admin_id bigint,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint care_sum_status_chk check (status in
    ('draft','in_review','published','withdrawn','superseded')),
  constraint care_sum_len_chk check (
    coalesce(char_length(service_window_text),0)   <= 200 and
    coalesce(char_length(completed_steps_text),0)  <= 600 and
    coalesce(char_length(family_actions_text),0)   <= 600 and
    coalesce(char_length(next_arrangement_text),0) <= 400 and
    coalesce(char_length(handover_status_text),0)  <= 300),
  constraint care_sum_withdraw_reason_chk check (
    status <> 'withdrawn' or withdraw_reason_code is not null),
  constraint care_sum_version_uniq unique (booking_id, version_number)
);
create index if not exists idx_care_sum_booking on care_family_summaries(booking_id);
create index if not exists idx_care_sum_status on care_family_summaries(status);

-- 一筆服務同時只能有一份 published 小結
create unique index if not exists uniq_care_sum_published_per_booking
  on care_family_summaries(booking_id) where status = 'published';

create or replace function care_guard_family_summary() returns trigger
language plpgsql as $$
begin
  -- 已發布的內容不可悄悄改寫：要改就撤回或建立新版本
  if old.status = 'published' then
    if new.service_window_text   is distinct from old.service_window_text
       or new.completed_steps_text  is distinct from old.completed_steps_text
       or new.family_actions_text   is distinct from old.family_actions_text
       or new.next_arrangement_text is distinct from old.next_arrangement_text
       or new.handover_status_text  is distinct from old.handover_status_text then
      raise exception '已發布的家屬小結不可修改內容，請撤回或建立新版本'
        using errcode = 'check_violation';
    end if;
  end if;

  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'     and new.status in ('in_review','superseded')) or
      (old.status = 'in_review' and new.status in ('published','draft','superseded')) or
      (old.status = 'published' and new.status in ('withdrawn','superseded')) or
      (old.status = 'withdrawn' and new.status in ('superseded'))
    ) then
      raise exception 'care_family_summary: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_sum_guard on care_family_summaries;
create trigger trg_care_sum_guard before update on care_family_summaries
  for each row execute function care_guard_family_summary();

-- ── 4. 異常事件（營運升級，非醫療分級、非急救）─────────────
create table if not exists care_incidents (
  id              bigint generated by default as identity primary key,
  booking_id      bigint not null references care_bookings(id) on delete restrict,
  companion_id    bigint references companions(id),
  related_event_id bigint references care_service_events(id),

  incident_type   text not null,
  severity        text not null default 'low',   -- 營運優先級，不是醫療嚴重度
  status          text not null default 'open',
  description     text,

  notification_status text not null default 'not_required',

  acknowledged_at   timestamptz,
  acknowledged_by_admin_id bigint,
  resolved_at       timestamptz,
  resolved_by_admin_id bigint,
  resolution_code   text,
  closed_at         timestamptz,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint care_inc_type_chk check (incident_type in (
    'family_contact_needed','schedule_or_handover_issue',
    'facility_process_follow_up','supervisor_attention_needed')),
  constraint care_inc_severity_chk check (severity in ('low','medium','high')),
  constraint care_inc_status_chk check (status in ('open','acknowledged','resolved','closed')),
  constraint care_inc_notif_chk check (notification_status in
    ('not_required','pending','prepared','sent_or_confirmed','failed')),
  constraint care_inc_desc_len_chk check (description is null or char_length(description) <= 300),
  constraint care_inc_resolution_chk check (
    status not in ('resolved','closed') or resolution_code is not null)
);
create index if not exists idx_care_inc_booking on care_incidents(booking_id);
create index if not exists idx_care_inc_status on care_incidents(status);
create index if not exists idx_care_inc_notif on care_incidents(notification_status);

create or replace function care_guard_incident() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'open'         and new.status in ('acknowledged','resolved')) or
      (old.status = 'acknowledged' and new.status in ('resolved')) or
      (old.status = 'resolved'     and new.status in ('closed'))
    ) then
      raise exception 'care_incident: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;

  -- 目前沒有正式的外部通知 provider：資料庫層直接擋下「已送出」
  -- 避免任何程式路徑產生假的已通知狀態。
  -- 未來接上 connector 時，改為由該 connector 的受控函式寫入。
  if new.notification_status = 'sent_or_confirmed'
     and old.notification_status is distinct from 'sent_or_confirmed' then
    raise exception '目前沒有正式通知管道，不可標記為已送出'
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_inc_guard on care_incidents;
create trigger trg_care_inc_guard before update on care_incidents
  for each row execute function care_guard_incident();

-- ── 5. 單筆服務的家屬授權（預設全部拒絕）───────────────────
-- 付款人／預約人／聯絡人都不會因為身分自動取得閱覽權，
-- 必須有一筆有效、未撤回的授權列。
create table if not exists care_service_authorizations (
  id            bigint generated by default as identity primary key,
  booking_id    bigint not null references care_bookings(id) on delete restrict,
  -- 對應 Supabase Auth 的會員；沒有帳號就無法被授權
  user_id       uuid not null,
  scope         text not null,

  granted_at    timestamptz not null default now(),
  granted_by_admin_id bigint,
  revoked_at    timestamptz,
  revoked_by_admin_id bigint,
  revoke_reason_code text,

  constraint care_auth_scope_chk check (scope in
    ('receive_service_notification','view_service_summary','view_service_photo')),
  constraint care_auth_uniq unique (booking_id, user_id, scope)
);
create index if not exists idx_care_auth_lookup
  on care_service_authorizations(user_id, booking_id) where revoked_at is null;

-- view_service_photo 本輪一律不啟用：資料庫層直接擋
create or replace function care_guard_authorization() returns trigger
language plpgsql as $$
begin
  if new.scope = 'view_service_photo' and new.revoked_at is null then
    raise exception '照片檢視權限本輪未啟用，需先完成法律、同意與私有儲存設計'
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_auth_guard on care_service_authorizations;
create trigger trg_care_auth_guard before insert or update on care_service_authorizations
  for each row execute function care_guard_authorization();

-- ── 6. 結算基礎（兼職）─────────────────────────────────────
-- ⚠️ 這裡「不」動既有的 care_bookings 結算欄位與 /admin/settlement。
-- 那套仍是目前實際在用的系統。本區是 Sprint D 要求的可稽核 line/batch
-- 基礎，為附加而非取代；是否整併為單一系統是後續的營運決定。
-- 兩套都不會自動付款，也不產生任何付款成功資訊。
create table if not exists care_settlement_batches (
  id             bigint generated by default as identity primary key,
  batch_no       text not null unique,
  period_start   date not null,
  period_end     date not null,
  status         text not null default 'draft',
  created_by_admin_id  bigint,
  approved_by_admin_id bigint,
  approved_at    timestamptz,
  published_at   timestamptz,
  closed_at      timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint care_batch_status_chk check (status in ('draft','approved','published','closed')),
  constraint care_batch_period_chk check (period_end >= period_start)
);
create index if not exists idx_care_batch_status on care_settlement_batches(status);

create table if not exists care_settlement_lines (
  id             bigint generated by default as identity primary key,
  booking_id     bigint not null references care_bookings(id) on delete restrict,
  companion_id   bigint not null references companions(id),
  batch_id       bigint references care_settlement_batches(id),

  employment_type_snapshot text not null,
  line_type      text not null,
  amount         integer not null,
  currency       text not null default 'TWD',
  -- 金額怎麼來的：快照計算依據，便於日後對帳
  basis_snapshot text not null,
  reason_code    text,

  status         text not null default 'pending_review',
  reviewed_by_admin_id bigint,
  reviewed_at    timestamptz,
  review_note    text,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint care_line_type_chk check (line_type in
    ('service_compensation','transport_reimbursement','manual_adjustment')),
  constraint care_line_status_chk check (status in
    ('pending_review','approved','rejected','published_to_staff','batched')),
  constraint care_line_employment_chk check (employment_type_snapshot in ('fulltime','parttime')),
  constraint care_line_currency_chk check (currency = 'TWD'),
  constraint care_line_amount_chk check (amount >= 0),
  constraint care_line_basis_len_chk check (char_length(basis_snapshot) between 1 and 200),
  constraint care_line_note_len_chk check (review_note is null or char_length(review_note) <= 200),
  -- 同一服務同一類型只能有一筆，避免重試或並發造成重複計算
  constraint care_line_uniq unique (booking_id, line_type)
);
create index if not exists idx_care_line_companion on care_settlement_lines(companion_id, status);
create index if not exists idx_care_line_batch on care_settlement_lines(batch_id);
create index if not exists idx_care_line_status on care_settlement_lines(status);

create or replace function care_guard_settlement_line() returns trigger
language plpgsql as $$
begin
  -- 全職不在本輪產生報酬 line
  if new.employment_type_snapshot = 'fulltime' then
    raise exception '全職陪診員本輪不產生結算 line，只提供服務統計'
      using errcode = 'check_violation';
  end if;

  if TG_OP = 'UPDATE' then
    -- 已發布給陪診員或已入批次的金額不可再改
    if old.status in ('published_to_staff','batched')
       and (new.amount is distinct from old.amount
            or new.line_type is distinct from old.line_type
            or new.basis_snapshot is distinct from old.basis_snapshot) then
      raise exception '已發布或已入批次的結算明細不可修改金額'
        using errcode = 'check_violation';
    end if;

    if new.status is distinct from old.status then
      if not (
        (old.status = 'pending_review'     and new.status in ('approved','rejected')) or
        (old.status = 'approved'           and new.status in ('batched','published_to_staff','pending_review')) or
        (old.status = 'batched'            and new.status in ('published_to_staff')) or
        (old.status = 'rejected'           and new.status in ('pending_review'))
      ) then
        raise exception 'care_settlement_line: 不允許的狀態轉換 % -> %', old.status, new.status
          using errcode = 'check_violation';
      end if;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_line_guard on care_settlement_lines;
create trigger trg_care_line_guard before insert or update on care_settlement_lines
  for each row execute function care_guard_settlement_line();

create or replace function care_guard_settlement_batch() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'     and new.status in ('approved')) or
      (old.status = 'approved'  and new.status in ('published','draft')) or
      (old.status = 'published' and new.status in ('closed'))
    ) then
      raise exception 'care_settlement_batch: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_batch_guard on care_settlement_batches;
create trigger trg_care_batch_guard before update on care_settlement_batches
  for each row execute function care_guard_settlement_batch();

-- ── 7. updated_at ──────────────────────────────────────────
drop trigger if exists trg_care_rec_touch on care_service_records;
create trigger trg_care_rec_touch before update on care_service_records
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_sum_touch on care_family_summaries;
create trigger trg_care_sum_touch before update on care_family_summaries
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_inc_touch on care_incidents;
create trigger trg_care_inc_touch before update on care_incidents
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_line_touch on care_settlement_lines;
create trigger trg_care_line_touch before update on care_settlement_lines
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_batch_touch on care_settlement_batches;
create trigger trg_care_batch_touch before update on care_settlement_batches
  for each row execute function care_touch_updated_at();

-- ── 8. RLS：預設全部拒絕 ───────────────────────────────────
-- 與 Sprint B 相同：後台／陪診員端／家屬端 API 都走 service_role，
-- 因此 RLS 是縱深防禦（擋 anon key 與 authenticated 直連），
-- 授權的實際強制點在 Service 層與 Route Handler。詳見 SECURITY.md。
do $$
declare t text;
begin
  foreach t in array array[
    'care_service_events','care_service_records','care_family_summaries',
    'care_incidents','care_service_authorizations',
    'care_settlement_lines','care_settlement_batches'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force row level security', t);
    execute format('revoke all on %I from anon, authenticated', t);
  end loop;
end $$;

-- 完成 ✓
