-- ═══════════════════════════════════════════════════════════
-- Sprint E：上線營運、受控通知、品質閉環與發版檢核
--
-- 冪等，可重複執行。
-- 前置：companion_care_schema.sql、care_operations_schema.sql、
--       care_staffing_schema.sql、care_fulfilment_schema.sql
--
-- ⚠️ 這一份**不會**發送任何外部訊息。
-- outbox 只是未來接上正式 provider 前的資料結構，
-- 資料庫層直接擋下任何「已送出／已送達」狀態（見第 4 節 trigger）。
-- ═══════════════════════════════════════════════════════════


-- ── 1. 站內通知：使用者收件匣 ──────────────────────────────
-- 不是服務紀錄、不是聊天、不是外部發送紀錄。
-- title/body 只放最低必要訊息；深層頁面必須再做一次授權檢查。
create table if not exists care_notifications (
  id            bigint generated by default as identity primary key,
  -- 收件人：Supabase Auth 會員（家屬）或陪診員，兩者擇一
  recipient_user_id   uuid,
  recipient_companion_id bigint references companions(id) on delete cascade,

  booking_id    bigint references care_bookings(id) on delete restrict,
  notification_type text not null,
  status        text not null default 'unread',

  -- 最小內容：不得放病況、診斷、姓名全名、電話、地址、金額、內部備註
  title         text not null,
  body          text,
  -- 深層連結只存路徑，不存 token、不存簽名網址
  link_path     text,

  created_by_admin_id bigint,
  source_reference text,

  created_at    timestamptz not null default now(),
  read_at       timestamptz,
  archived_at   timestamptz,
  updated_at    timestamptz not null default now(),

  constraint care_notif_status_chk check (status in ('unread','read','archived')),
  constraint care_notif_type_chk check (notification_type in (
    'service_event_published','family_summary_published','family_action_needed',
    'incident_contact_requested','feedback_requested','quality_follow_up_requested',
    'staff_schedule_updated','staff_time_off_reviewed','settlement_published')),
  -- 一定要有收件人，而且只能是其中一種身分
  constraint care_notif_recipient_chk check (
    (recipient_user_id is not null and recipient_companion_id is null) or
    (recipient_user_id is null and recipient_companion_id is not null)),
  -- 內容長度上限：擋下有人把服務紀錄整段塞進來
  constraint care_notif_title_len_chk check (char_length(title) <= 60),
  constraint care_notif_body_len_chk check (body is null or char_length(body) <= 200),
  constraint care_notif_link_chk check (link_path is null or link_path like '/%')
);
create index if not exists idx_care_notif_user
  on care_notifications(recipient_user_id, status, created_at desc)
  where recipient_user_id is not null;
create index if not exists idx_care_notif_companion
  on care_notifications(recipient_companion_id, status, created_at desc)
  where recipient_companion_id is not null;
create index if not exists idx_care_notif_booking on care_notifications(booking_id);


-- ── 2. 通知偏好 ────────────────────────────────────────────
-- 外部通道預設關閉，而且這裡**不存**任何外部帳號、手機、Email 或 token。
create table if not exists care_notification_preferences (
  id            bigint generated by default as identity primary key,
  user_id       uuid,
  companion_id  bigint references companions(id) on delete cascade,
  category      text not null,

  in_app_enabled boolean not null default true,
  -- 沒有可追溯的明確 opt-in 就不得建立外部發送
  external_channel_opt_in boolean not null default false,
  external_channel_kind text,
  -- 外部通道尚未設定；這欄只記錄狀態，不記錄帳號
  external_channel_state text not null default 'not_configured',

  opt_in_at     timestamptz,
  opt_out_at    timestamptz,
  policy_version_id bigint,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint care_notif_pref_category_chk check (category in (
    'service_progress','summary_published','action_needed',
    'feedback_request','quality_follow_up','schedule','settlement')),
  constraint care_notif_pref_state_chk check (external_channel_state in
    ('not_configured','pending_approval','approved')),
  constraint care_notif_pref_subject_chk check (
    (user_id is not null and companion_id is null) or
    (user_id is null and companion_id is not null))
);
create unique index if not exists uniq_care_notif_pref_user
  on care_notification_preferences(user_id, category) where user_id is not null;
create unique index if not exists uniq_care_notif_pref_companion
  on care_notification_preferences(companion_id, category) where companion_id is not null;


-- ── 3. 通知 outbox（provider-neutral，本輪不啟用） ─────────
-- 本輪沒有 worker、沒有排程、沒有輪詢、不呼叫任何第三方 API。
create table if not exists care_notification_outbox (
  id            bigint generated by default as identity primary key,
  notification_id bigint not null references care_notifications(id) on delete cascade,
  channel       text not null default 'in_app',
  status        text not null default 'not_configured',
  suppression_reason_code text,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  suppressed_at timestamptz,
  suppressed_by_admin_id bigint,

  constraint care_outbox_channel_chk check (channel in
    ('in_app','external_pending_configuration')),
  -- 刻意沒有 sent / delivered：沒有 provider 就不會有那些狀態
  constraint care_outbox_status_chk check (status in
    ('not_configured','queued_for_approved_provider','suppressed','cancelled')),
  constraint care_outbox_uniq unique (notification_id, channel)
);
create index if not exists idx_care_outbox_status on care_notification_outbox(status, created_at desc);


-- ── 4. 資料庫層擋下「假裝已送出」 ─────────────────────────
create or replace function care_guard_outbox() returns trigger
language plpgsql as $$
begin
  -- 這裡刻意用文字比對而不是只靠 check constraint：
  -- 就算日後有人放寬 constraint，這個 trigger 仍會擋下來。
  if new.status in ('sent','delivered','sent_or_confirmed','success') then
    raise exception '沒有已核准的外部通知 provider，不可標記為已送出';
  end if;
  if new.channel = 'external_pending_configuration'
     and new.status = 'queued_for_approved_provider' then
    raise exception '外部通知通道尚未設定，不可排入待送佇列';
  end if;
  return new;
end $$;
drop trigger if exists trg_care_outbox_guard on care_notification_outbox;
create trigger trg_care_outbox_guard before insert or update on care_notification_outbox
  for each row execute function care_guard_outbox();

-- 通知本身：已讀時間由資料庫寫，不由 client 指定
create or replace function care_guard_notification() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.read_at := null;
    new.archived_at := null;
    return new;
  end if;
  -- 內容一旦建立就不可改寫：通知不是可以事後編輯的訊息
  if new.title is distinct from old.title
     or new.body is distinct from old.body
     or new.link_path is distinct from old.link_path
     or new.recipient_user_id is distinct from old.recipient_user_id
     or new.recipient_companion_id is distinct from old.recipient_companion_id then
    raise exception '通知內容與收件人不可修改';
  end if;
  if new.status = 'read' and old.status = 'unread' then new.read_at := now(); end if;
  if new.status = 'archived' and old.status <> 'archived' then new.archived_at := now(); end if;
  return new;
end $$;
drop trigger if exists trg_care_notification_guard on care_notifications;
create trigger trg_care_notification_guard before insert or update on care_notifications
  for each row execute function care_guard_notification();

-- 通知不可刪除：刪掉就查不出誰在什麼時候被通知過什麼
create or replace function care_block_delete() returns trigger
language plpgsql as $$
begin
  raise exception '這張表不允許刪除，請改用狀態變更保留軌跡';
end $$;
drop trigger if exists trg_care_notification_nodelete on care_notifications;
create trigger trg_care_notification_nodelete before delete on care_notifications
  for each row execute function care_block_delete();


-- ── 5. 家屬服務回饋 ────────────────────────────────────────
create table if not exists care_feedback_requests (
  id            bigint generated by default as identity primary key,
  booking_id    bigint not null references care_bookings(id) on delete restrict,
  recipient_user_id uuid not null,
  summary_id    bigint references care_family_summaries(id) on delete set null,

  status        text not null default 'eligible',
  expires_at    timestamptz,
  form_version  text not null default 'v1',

  created_at    timestamptz not null default now(),
  presented_at  timestamptz,
  completed_at  timestamptz,
  suppressed_at timestamptz,
  suppress_reason_code text,
  updated_at    timestamptz not null default now(),

  constraint care_fbreq_status_chk check (status in
    ('eligible','presented','completed','expired','suppressed')),
  -- 同一位家屬對同一筆服務只會有一張邀請
  constraint care_fbreq_uniq unique (booking_id, recipient_user_id)
);
create index if not exists idx_care_fbreq_user
  on care_feedback_requests(recipient_user_id, status);

create table if not exists care_feedback (
  id            bigint generated by default as identity primary key,
  request_id    bigint not null references care_feedback_requests(id) on delete restrict,
  booking_id    bigint not null references care_bookings(id) on delete restrict,
  submitted_by_user_id uuid not null,

  -- 三個面向，1–5；刻意不做總分排名，也不對外公開
  score_reassurance smallint not null,
  score_communication smallint not null,
  score_process_support smallint not null,
  -- 補充意見：限長，UI 與後端都會提示不要填病況與個資
  comment       text,

  status        text not null default 'submitted',
  reviewed_by_admin_id bigint,
  reviewed_at   timestamptz,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint care_fb_status_chk check (status in ('submitted','under_review','closed')),
  constraint care_fb_score1_chk check (score_reassurance between 1 and 5),
  constraint care_fb_score2_chk check (score_communication between 1 and 5),
  constraint care_fb_score3_chk check (score_process_support between 1 and 5),
  constraint care_fb_comment_len_chk check (comment is null or char_length(comment) <= 300),
  -- 一張邀請只收一份回饋：重試與並發都不會產生第二筆
  constraint care_fb_request_uniq unique (request_id)
);
create index if not exists idx_care_fb_booking on care_feedback(booking_id);


-- ── 6. 意見／申訴追蹤 ──────────────────────────────────────
-- 這不是醫療申訴、不是法律裁定，也不對事實或責任做任何自動判斷。
create table if not exists care_concerns (
  id            bigint generated by default as identity primary key,
  booking_id    bigint references care_bookings(id) on delete restrict,
  source        text not null,
  -- 來源人（擇一或都沒有：營運自建）
  source_user_id uuid,
  source_companion_id bigint references companions(id) on delete set null,
  feedback_id   bigint references care_feedback(id) on delete set null,

  category      text not null,
  status        text not null default 'open',
  owner_admin_id bigint,
  due_date      date,

  description   text not null,
  resolution_code text,
  internal_note text,

  created_at    timestamptz not null default now(),
  acknowledged_at timestamptz,
  resolved_at   timestamptz,
  closed_at     timestamptz,
  updated_at    timestamptz not null default now(),

  constraint care_concern_source_chk check (source in
    ('family_feedback','family_submitted','staff_submitted','operations_created')),
  constraint care_concern_category_chk check (category in
    ('communication','schedule','handover','service_experience','privacy_request','other_non_medical')),
  constraint care_concern_status_chk check (status in
    ('open','acknowledged','in_follow_up','resolved','closed')),
  constraint care_concern_desc_len_chk check (char_length(description) <= 500),
  constraint care_concern_note_len_chk check (internal_note is null or char_length(internal_note) <= 500)
);
create index if not exists idx_care_concern_status on care_concerns(status, due_date);
create index if not exists idx_care_concern_source_user
  on care_concerns(source_user_id) where source_user_id is not null;


-- ── 7. 品質覆核與改善追蹤 ──────────────────────────────────
-- 不是公開評分、不是人員排行，也不會自動產生人事處分或排班限制。
create table if not exists care_quality_reviews (
  id            bigint generated by default as identity primary key,
  booking_id    bigint not null references care_bookings(id) on delete restrict,
  reviewer_admin_id bigint,
  status        text not null default 'pending',

  -- 結構化 checklist：可為 null 代表尚未評
  chk_events_complete boolean,
  chk_record_on_time boolean,
  chk_summary_clear boolean,
  chk_authorization_correct boolean,
  chk_communication_done boolean,

  internal_note text,

  created_at    timestamptz not null default now(),
  started_at    timestamptz,
  completed_at  timestamptz,
  updated_at    timestamptz not null default now(),

  constraint care_qr_status_chk check (status in
    ('pending','in_review','completed','follow_up_required')),
  constraint care_qr_note_len_chk check (internal_note is null or char_length(internal_note) <= 500),
  -- 一筆服務同時只會有一份進行中的品質覆核
  constraint care_qr_booking_uniq unique (booking_id)
);
create index if not exists idx_care_qr_status on care_quality_reviews(status);

create table if not exists care_quality_follow_ups (
  id            bigint generated by default as identity primary key,
  review_id     bigint not null references care_quality_reviews(id) on delete restrict,
  -- 改善責任人：陪診員或後台人員
  owner_companion_id bigint references companions(id) on delete set null,
  owner_admin_id bigint,

  action_code   text not null,
  -- 給陪診員看的摘要：不含家屬原文、不含其他人的品質資料
  staff_visible_note text,
  due_date      date,
  status        text not null default 'open',

  created_at    timestamptz not null default now(),
  completed_at  timestamptz,
  verified_at   timestamptz,
  verified_by_admin_id bigint,
  updated_at    timestamptz not null default now(),

  constraint care_qfu_action_chk check (action_code in
    ('record_timeliness','event_completeness','family_communication',
     'handover_process','authorization_handling','other_process')),
  constraint care_qfu_status_chk check (status in ('open','in_progress','completed','verified','cancelled')),
  constraint care_qfu_note_len_chk check (
    staff_visible_note is null or char_length(staff_visible_note) <= 200)
);
create index if not exists idx_care_qfu_owner_companion
  on care_quality_follow_ups(owner_companion_id, status) where owner_companion_id is not null;


-- ── 8. 版本化政策文件與接受紀錄 ────────────────────────────
-- ⚠️ 本輪只建立版本／發布／接受的管理能力。
--    正式條款文字必須由營運與法務確認後填入，系統不自行撰寫，
--    也不聲稱任何內容具備法律效力。
create table if not exists care_policy_versions (
  id            bigint generated by default as identity primary key,
  policy_kind   text not null,
  version_label text not null,
  status        text not null default 'draft',
  -- 正文由人工填入；draft 階段可以是空的
  body_text     text,
  effective_from date,

  created_at    timestamptz not null default now(),
  created_by_admin_id bigint,
  published_at  timestamptz,
  published_by_admin_id bigint,
  retired_at    timestamptz,
  updated_at    timestamptz not null default now(),

  constraint care_policy_kind_chk check (policy_kind in
    ('terms_of_service','privacy_notice','cancellation_rules','family_handover_notice')),
  constraint care_policy_status_chk check (status in ('draft','published','retired')),
  constraint care_policy_uniq unique (policy_kind, version_label)
);
-- 同一種文件同時只能有一個已發布版本
create unique index if not exists uniq_care_policy_published
  on care_policy_versions(policy_kind) where status = 'published';

create table if not exists care_policy_acceptances (
  id            bigint generated by default as identity primary key,
  policy_version_id bigint not null references care_policy_versions(id) on delete restrict,
  user_id       uuid,
  companion_id  bigint references companions(id) on delete cascade,
  booking_id    bigint references care_bookings(id) on delete set null,

  accepted_at   timestamptz not null default now(),
  accept_source text not null default 'web',

  constraint care_policy_acc_subject_chk check (
    (user_id is not null and companion_id is null) or
    (user_id is null and companion_id is not null)),
  constraint care_policy_acc_source_chk check (accept_source in ('web','admin_recorded','import'))
);
create unique index if not exists uniq_care_policy_acc_user
  on care_policy_acceptances(policy_version_id, user_id) where user_id is not null;
create unique index if not exists uniq_care_policy_acc_companion
  on care_policy_acceptances(policy_version_id, companion_id) where companion_id is not null;


-- ── 9. 資料保留／刪除工作清單 ──────────────────────────────
-- ⚠️ 本輪**不刪除任何真實資料**，只建立可追蹤的待處理清單。
--    真正的刪除／匿名化／匯出要等法務、營運與備份策略確認後另做。
create table if not exists care_data_lifecycle_reviews (
  id            bigint generated by default as identity primary key,
  resource_kind text not null,
  booking_id    bigint references care_bookings(id) on delete set null,
  resource_id   bigint,

  status        text not null default 'pending',
  due_date      date,
  reason_code   text not null,
  reviewer_admin_id bigint,
  reviewed_at   timestamptz,
  note          text,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint care_dlr_kind_chk check (resource_kind in
    ('service_record','family_summary','service_event','incident',
     'feedback','concern','notification','settlement_line')),
  constraint care_dlr_status_chk check (status in
    ('pending','reviewed','retain','pending_legal_confirmation')),
  constraint care_dlr_reason_chk check (reason_code in
    ('retention_period_review','user_request','operational_cleanup','legal_hold')),
  constraint care_dlr_note_len_chk check (note is null or char_length(note) <= 300)
);
create index if not exists idx_care_dlr_status on care_data_lifecycle_reviews(status, due_date);


-- ── 10. 狀態機 trigger ─────────────────────────────────────
create or replace function care_guard_feedback() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    return new;
  end if;
  -- 分數與意見送出後不可改：改了就不是家屬當時說的話
  if new.score_reassurance is distinct from old.score_reassurance
     or new.score_communication is distinct from old.score_communication
     or new.score_process_support is distinct from old.score_process_support
     or new.comment is distinct from old.comment then
    raise exception '已送出的回饋內容不可修改';
  end if;
  if old.status = 'closed' and new.status <> 'closed' then
    raise exception '已結案的回饋不可重新開啟';
  end if;
  return new;
end $$;
drop trigger if exists trg_care_feedback_guard on care_feedback;
create trigger trg_care_feedback_guard before insert or update on care_feedback
  for each row execute function care_guard_feedback();

create or replace function care_guard_concern() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    if new.status <> 'open' then
      raise exception '意見案件一律從 open 開始';
    end if;
    return new;
  end if;
  if old.status in ('closed') and new.status <> 'closed' then
    raise exception '已結案的意見案件不可重新開啟';
  end if;
  if new.status = 'acknowledged' and old.status <> 'open' then
    raise exception '只有 open 可以受理';
  end if;
  if new.status = 'acknowledged' then new.acknowledged_at := coalesce(old.acknowledged_at, now()); end if;
  if new.status = 'resolved' then
    if old.status not in ('acknowledged','in_follow_up') then
      raise exception '要先受理才能標記為已處理';
    end if;
    new.resolved_at := coalesce(old.resolved_at, now());
  end if;
  if new.status = 'closed' then
    if old.status <> 'resolved' then
      raise exception '要先標記為已處理才能結案';
    end if;
    new.closed_at := coalesce(old.closed_at, now());
  end if;
  return new;
end $$;
drop trigger if exists trg_care_concern_guard on care_concerns;
create trigger trg_care_concern_guard before insert or update on care_concerns
  for each row execute function care_guard_concern();

create or replace function care_guard_quality_review() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then return new; end if;
  if old.status = 'completed' and new.status <> 'completed' then
    raise exception '已完成的品質覆核不可退回，請另建改善任務';
  end if;
  if new.status in ('completed','follow_up_required') then
    new.completed_at := coalesce(old.completed_at, now());
  end if;
  return new;
end $$;
drop trigger if exists trg_care_qr_guard on care_quality_reviews;
create trigger trg_care_qr_guard before insert or update on care_quality_reviews
  for each row execute function care_guard_quality_review();

create or replace function care_guard_policy_version() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    if new.status <> 'draft' then
      raise exception '政策版本一律從 draft 開始，發布是另一個動作';
    end if;
    return new;
  end if;
  -- 已發布的正文不可悄悄改寫：使用者接受的是他當時看到的那份
  if old.status = 'published' and new.body_text is distinct from old.body_text then
    raise exception '已發布的政策內容不可修改，請建立新版本';
  end if;
  if new.status = 'published' and old.status = 'draft' then
    if new.body_text is null or char_length(btrim(new.body_text)) = 0 then
      raise exception '政策正文是空的，不可發布';
    end if;
    new.published_at := coalesce(old.published_at, now());
  end if;
  if old.status = 'retired' and new.status <> 'retired' then
    raise exception '已停用的版本不可復原，請建立新版本';
  end if;
  return new;
end $$;
drop trigger if exists trg_care_policy_guard on care_policy_versions;
create trigger trg_care_policy_guard before insert or update on care_policy_versions
  for each row execute function care_guard_policy_version();

-- 接受紀錄是既成事實，不可修改也不可刪除
create or replace function care_guard_policy_acceptance() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    new.accepted_at := now();
    return new;
  end if;
  raise exception '政策接受紀錄不可修改';
end $$;
drop trigger if exists trg_care_policy_acc_guard on care_policy_acceptances;
create trigger trg_care_policy_acc_guard before insert or update on care_policy_acceptances
  for each row execute function care_guard_policy_acceptance();
drop trigger if exists trg_care_policy_acc_nodelete on care_policy_acceptances;
create trigger trg_care_policy_acc_nodelete before delete on care_policy_acceptances
  for each row execute function care_block_delete();


-- ── 11. updated_at ─────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'care_notifications','care_notification_preferences','care_notification_outbox',
    'care_feedback_requests','care_feedback','care_concerns',
    'care_quality_reviews','care_quality_follow_ups',
    'care_policy_versions','care_data_lifecycle_reviews'
  ] loop
    execute format('drop trigger if exists trg_%s_touch on %I', t, t);
    execute format(
      'create trigger trg_%s_touch before update on %I for each row execute function care_touch_updated_at()',
      t, t);
  end loop;
end $$;


-- ── 12. 政策版本種子：只建 draft，正文留空 ────────────────
-- 刻意不寫任何條款文字。法務確認前，release readiness 會標示為 blocked。
insert into care_policy_versions (policy_kind, version_label, status, body_text)
select k, 'v1-draft', 'draft', null
from unnest(array['terms_of_service','privacy_notice','cancellation_rules','family_handover_notice']) as k
where not exists (
  select 1 from care_policy_versions p where p.policy_kind = k
);


-- ── 13. RLS：預設全部拒絕 ─────────────────────────────────
-- 與 Sprint B/C/D 相同：伺服器端走 service_role，
-- RLS 是縱深防禦，授權的實際強制點在 Service 層與 Route Handler。
do $$
declare t text;
begin
  foreach t in array array[
    'care_notifications','care_notification_preferences','care_notification_outbox',
    'care_feedback_requests','care_feedback','care_concerns',
    'care_quality_reviews','care_quality_follow_ups',
    'care_policy_versions','care_policy_acceptances','care_data_lifecycle_reviews'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force row level security', t);
    execute format('revoke all on %I from anon, authenticated', t);
  end loop;
end $$;

-- 完成 ✓
