-- ===========================================================
-- Sprint B：陪診營運（初評 → 案件 → 報價）
-- 在 Supabase SQL Editor 執行此檔案即可。可重複執行。
--
-- 責任邊界（重要）：
--   care_intakes         人工初評所需的「最低必要服務安排資訊」
--   care_cases           營運案件的生命週期
--   care_quote_estimates 版本化的報價快照
--   care_quote_items     報價的結構化明細（不用 JSON 塞整張表單）
--
-- 這三張表都「不是醫療紀錄」：不存病史、診斷、處方、劑量、治療建議、
-- 身分證/健保卡號、病歷影像或任何支付憑證。
--
-- 與既有 care_bookings 的關係：
--   care_bookings 是「已成立的正式預約」，責任不變，本檔案不修改它。
--   care_intakes 是「尚未成立預約的初步需求」，是本流程的 root。
--   目前資料庫沒有 service_requests / AppUser / Party 等表，
--   因此以 care_intakes 自身作為 root，並保留 converted_booking_id
--   供未來與正式預約串接（本輪不寫入）。
-- ===========================================================

-- ── 1. 初評 care_intakes ───────────────────────────────────
create table if not exists care_intakes (
  id                        bigint generated by default as identity primary key,

  service_scenario          text not null,
  mobility_support_level    text not null,
  transport_support_requested boolean not null default false,

  hospital_name             text not null,
  county                    text not null,
  scheduled_service_date    date not null,
  time_preference           text not null default 'unspecified',

  contact_name              text not null,
  contact_phone             text not null,
  contact_line_id           text,
  contact_preference        text not null default 'phone',
  relationship_to_beneficiary text not null,

  -- 受限字數的補充需求。刻意不叫 medical_history：
  -- 用途僅限「當天流程協助」，不得存病史/診斷/用藥。
  limited_support_note      text,

  status                    text not null default 'submitted',
  decline_reason_code       text,
  review_note               text,

  -- 來源與防濫用。只存 IP 的雜湊，不存原始 IP。
  source                    text not null default 'public_web',
  submitter_ip_hash         text,

  reviewed_by_admin_id      bigint,
  reviewed_at               timestamptz,
  converted_booking_id      bigint references care_bookings(id),

  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),

  constraint care_intakes_scenario_chk check (service_scenario in
    ('routine_visit','visit_with_tests','multi_department_or_full_day','post_procedure_discharge','unsure')),
  constraint care_intakes_mobility_chk check (mobility_support_level in
    ('independent','assistive_device','wheelchair','manual_review_required')),
  constraint care_intakes_time_pref_chk check (time_preference in
    ('morning','afternoon','all_day','unspecified')),
  constraint care_intakes_contact_pref_chk check (contact_preference in ('phone','line')),
  constraint care_intakes_status_chk check (status in
    ('submitted','in_review','needs_more_information','declined','converted_to_case')),
  -- 受限字數：資料庫層也要擋，不能只靠前端
  constraint care_intakes_note_len_chk check (limited_support_note is null or char_length(limited_support_note) <= 200),
  constraint care_intakes_review_note_len_chk check (review_note is null or char_length(review_note) <= 500),
  -- 婉拒一定要有原因 code
  constraint care_intakes_decline_reason_chk check (
    status <> 'declined' or decline_reason_code is not null)
);

create index if not exists idx_care_intakes_status on care_intakes(status);
create index if not exists idx_care_intakes_created on care_intakes(created_at desc);
create index if not exists idx_care_intakes_date on care_intakes(scheduled_service_date);
-- 防濫用查詢用
create index if not exists idx_care_intakes_ip_recent on care_intakes(submitter_ip_hash, created_at desc);

-- ── 2. 案件 care_cases ─────────────────────────────────────
create table if not exists care_cases (
  id                   bigint generated by default as identity primary key,
  case_no              text not null unique,
  -- 一筆初評最多只能轉出一個案件
  intake_id            bigint not null unique references care_intakes(id) on delete restrict,
  status               text not null default 'needs_assessment',
  owner_admin_id       bigint,
  cancel_reason_code   text,
  cancelled_at         timestamptz,
  -- 付款為人工確認，本輪不串金流；這裡只記錄「誰按下確認」
  payment_marked_by    text,
  payment_marked_at    timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  constraint care_cases_status_chk check (status in
    ('needs_assessment','awaiting_quote_confirmation','awaiting_payment','ready_to_match','cancelled')),
  constraint care_cases_cancel_reason_chk check (
    status <> 'cancelled' or cancel_reason_code is not null)
);

create index if not exists idx_care_cases_status on care_cases(status);
create index if not exists idx_care_cases_created on care_cases(created_at desc);

-- ── 3. 報價 care_quote_estimates ───────────────────────────
create table if not exists care_quote_estimates (
  id                      bigint generated by default as identity primary key,
  care_case_id            bigint not null references care_cases(id) on delete cascade,
  version                 integer not null,
  status                  text not null default 'draft',
  currency                text not null default 'TWD',

  -- 服務方案的 immutable snapshot：報價當下把方案名稱與價格複製下來，
  -- 日後 care_services 改價不影響已發出的報價。
  service_code            text not null,
  service_name_snapshot   text not null,
  base_fee                integer not null,

  -- 預估類項目：必須寫清楚計價方式，不可只寫「另計」
  travel_estimate_amount  integer not null default 0,
  travel_estimate_basis   text not null,
  -- 超時規則快照，同樣不可只寫「另計」
  overtime_rule_snapshot  text not null,

  total_estimate          integer not null,
  valid_until             date not null,

  sent_at                 timestamptz,
  confirmed_at            timestamptz,
  -- 確認人：本輪沒有 Party/Authorization 模型，只記錄由誰代為確認，
  -- 不假設付款人具有所有資料權。
  confirmed_by_label      text,
  confirmed_by_admin_id   bigint,
  expired_at              timestamptz,
  cancelled_at            timestamptz,
  cancel_reason_code      text,

  created_by_admin_id     bigint,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  constraint care_quotes_status_chk check (status in
    ('draft','sent','confirmed','expired','cancelled')),
  constraint care_quotes_currency_chk check (currency = 'TWD'),
  constraint care_quotes_amounts_chk check (
    base_fee >= 0 and travel_estimate_amount >= 0 and total_estimate >= 0),
  constraint care_quotes_basis_len_chk check (char_length(travel_estimate_basis) between 1 and 300),
  constraint care_quotes_overtime_len_chk check (char_length(overtime_rule_snapshot) between 1 and 300),
  constraint care_quotes_version_uniq unique (care_case_id, version)
);

create index if not exists idx_care_quotes_case on care_quote_estimates(care_case_id);
create index if not exists idx_care_quotes_status on care_quote_estimates(status);

-- 一個案件同時最多只能有一份 confirmed 報價
create unique index if not exists uniq_care_quote_confirmed_per_case
  on care_quote_estimates(care_case_id) where status = 'confirmed';

-- ── 4. 報價明細 care_quote_items ───────────────────────────
create table if not exists care_quote_items (
  id            bigint generated by default as identity primary key,
  quote_id      bigint not null references care_quote_estimates(id) on delete cascade,
  item_code     text not null,
  label_snapshot text not null,
  unit_price    integer not null,
  quantity      integer not null default 1,
  line_total    integer not null,
  created_at    timestamptz not null default now(),

  constraint care_quote_items_amounts_chk check (unit_price >= 0 and quantity > 0 and line_total >= 0)
);
create index if not exists idx_care_quote_items_quote on care_quote_items(quote_id);

-- ── 5. updated_at ──────────────────────────────────────────
create or replace function care_touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists trg_care_intakes_touch on care_intakes;
create trigger trg_care_intakes_touch before update on care_intakes
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_cases_touch on care_cases;
create trigger trg_care_cases_touch before update on care_cases
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_quotes_touch on care_quote_estimates;
create trigger trg_care_quotes_touch before update on care_quote_estimates
  for each row execute function care_touch_updated_at();

-- ── 6. 狀態機（資料庫端強制，不只靠 UI 與 Service）─────────
create or replace function care_guard_intake_status() returns trigger
language plpgsql as $$
begin
  if new.status = old.status then return new; end if;
  if not (
    (old.status = 'submitted'              and new.status in ('in_review','declined')) or
    (old.status = 'in_review'              and new.status in ('needs_more_information','declined','converted_to_case')) or
    (old.status = 'needs_more_information' and new.status in ('in_review','declined'))
  ) then
    raise exception 'care_intake: 不允許的狀態轉換 % -> %', old.status, new.status
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_intakes_status on care_intakes;
create trigger trg_care_intakes_status before update on care_intakes
  for each row execute function care_guard_intake_status();

create or replace function care_guard_case_status() returns trigger
language plpgsql as $$
begin
  if new.status = old.status then return new; end if;
  if not (
    (old.status = 'needs_assessment'           and new.status in ('awaiting_quote_confirmation','cancelled')) or
    (old.status = 'awaiting_quote_confirmation' and new.status in ('awaiting_payment','needs_assessment','cancelled')) or
    (old.status = 'awaiting_payment'           and new.status in ('ready_to_match','cancelled')) or
    (old.status = 'ready_to_match'             and new.status in ('cancelled'))
  ) then
    raise exception 'care_case: 不允許的狀態轉換 % -> %', old.status, new.status
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_cases_status on care_cases;
create trigger trg_care_cases_status before update on care_cases
  for each row execute function care_guard_case_status();

-- 已確認／已過期的報價不可被無聲改寫
create or replace function care_guard_quote_write() returns trigger
language plpgsql as $$
begin
  if old.status in ('confirmed','expired','cancelled') then
    -- 這些狀態只允許「不改動金額與快照」的極少數欄位變動
    if new.base_fee is distinct from old.base_fee
       or new.total_estimate is distinct from old.total_estimate
       or new.travel_estimate_amount is distinct from old.travel_estimate_amount
       or new.service_code is distinct from old.service_code
       or new.service_name_snapshot is distinct from old.service_name_snapshot
       or new.overtime_rule_snapshot is distinct from old.overtime_rule_snapshot
       or new.travel_estimate_basis is distinct from old.travel_estimate_basis
       or new.valid_until is distinct from old.valid_until then
      raise exception 'care_quote: 狀態為 % 的報價不可修改金額或快照內容', old.status
        using errcode = 'check_violation';
    end if;
  end if;

  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'  and new.status in ('sent','cancelled')) or
      (old.status = 'sent'   and new.status in ('confirmed','expired','cancelled')) or
      (old.status = 'confirmed' and new.status in ('cancelled'))
    ) then
      raise exception 'care_quote: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_quotes_guard on care_quote_estimates;
create trigger trg_care_quotes_guard before update on care_quote_estimates
  for each row execute function care_guard_quote_write();

-- 已送出的報價，明細不可再變動
create or replace function care_guard_quote_items() returns trigger
language plpgsql as $$
declare q_status text;
begin
  select status into q_status from care_quote_estimates
   where id = coalesce(new.quote_id, old.quote_id);
  if q_status is not null and q_status <> 'draft' then
    raise exception 'care_quote_items: 報價已為 %，明細不可再變動', q_status
      using errcode = 'check_violation';
  end if;
  return coalesce(new, old);
end $$;

drop trigger if exists trg_care_quote_items_guard on care_quote_items;
create trigger trg_care_quote_items_guard before insert or update or delete on care_quote_items
  for each row execute function care_guard_quote_items();

-- ── 7. RLS：預設全部拒絕 ───────────────────────────────────
-- 注意：本專案的後台 API 目前一律使用 service_role client，
-- service_role 會繞過 RLS，因此 RLS 在此是「縱深防禦」：
-- 它確保就算有人拿到 anon key（前台會用到）或 authenticated 身分，
-- 也讀不到任何一筆陪診營運資料。授權的實際強制點在 Service 層與
-- Route Handler 的 requirePermission()。詳見 SECURITY.md。
alter table care_intakes         enable row level security;
alter table care_cases           enable row level security;
alter table care_quote_estimates enable row level security;
alter table care_quote_items     enable row level security;

alter table care_intakes         force row level security;
alter table care_cases           force row level security;
alter table care_quote_estimates force row level security;
alter table care_quote_items     force row level security;

-- 不建立任何 policy = anon / authenticated 一律拒絕（含 SELECT）
revoke all on care_intakes         from anon, authenticated;
revoke all on care_cases           from anon, authenticated;
revoke all on care_quote_estimates from anon, authenticated;
revoke all on care_quote_items     from anon, authenticated;

-- ── 8. 後台權限 ────────────────────────────────────────────
-- 僅新增權限「定義」；不自動賦予任何既有角色（super_admin 的 'all' 本來就涵蓋）。
-- 要指派給 operations / customer_service 等角色，請到後台「帳號管理」勾選，
-- 或執行 OPERATIONS.md 中列出的 seed 語句。

-- 完成 ✓
