-- ===========================================================
-- Sprint C：陪診員管理、人工媒合與班表
-- 在 Supabase SQL Editor 執行。可重複執行。
--
-- 對應關係（本專案沒有規格書假設的那套命名）：
--   StaffProfile  → companions
--   Assignment    → care_bookings.companion_id（設值即為正式指派）
--   ServiceTask   → 沒有獨立表，由 care_bookings.status 承擔
--   Staff Portal  → /companion
--
-- 本檔案「正規化並延伸」既有欄位，不刪除它們：
--   companions.employment_type → staff_employment_terms（版本化、有期間）
--   companions.service_areas   → staff_service_regions（正規化多對多）
--   companion_availability     → 保留（單日時段），另加週期性規則
--
-- 需先執行 companion_care_schema.sql 與 care_operations_schema.sql
-- ===========================================================

-- ── 0. 案件 → 正式服務的橋接 ──────────────────────────────
-- Sprint B 的 care_cases 沒有連到 care_bookings，因此無從派工。
-- 這裡補一個唯一關聯：媒合前先把案件「實體化」成一筆正式服務。
alter table care_cases add column if not exists booking_id bigint references care_bookings(id);
create unique index if not exists uniq_care_case_booking
  on care_cases(booking_id) where booking_id is not null;

-- ── 1. 僱用型態（版本化）──────────────────────────────────
create table if not exists staff_employment_terms (
  id             bigint generated by default as identity primary key,
  companion_id   bigint not null references companions(id) on delete cascade,
  employment_type text not null,
  status         text not null default 'active',
  effective_from date not null,
  effective_to   date,
  note           text,
  created_by_admin_id bigint,
  ended_by_admin_id   bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint set_type_chk check (employment_type in ('full_time', 'part_time')),
  constraint set_status_chk check (status in ('active', 'paused', 'ended')),
  constraint set_period_chk check (effective_to is null or effective_to >= effective_from),
  constraint set_note_len_chk check (note is null or char_length(note) <= 200)
);
create index if not exists idx_set_companion on staff_employment_terms(companion_id, status);

-- 同一人同時只能有一筆未結束的僱用條件
create unique index if not exists uniq_set_open_per_companion
  on staff_employment_terms(companion_id) where status <> 'ended';

-- ── 2. 服務區域（正規化）──────────────────────────────────
create table if not exists staff_service_regions (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  region       text not null,
  created_by_admin_id bigint,
  created_at   timestamptz not null default now(),
  unique (companion_id, region)
);
create index if not exists idx_ssr_region on staff_service_regions(region);

-- ── 3. 能力與驗證 ──────────────────────────────────────────
-- ⚠️ 這些不是醫療執照，也不是醫療資格，不得用於宣稱醫療專業。
create table if not exists staff_capabilities (
  code        text primary key,
  label       text not null,
  description text,
  sort_order  integer default 0
);

insert into staff_capabilities (code, label, description, sort_order) values
  ('general_outpatient_flow', '一般門診流程協助', '報到、候診、批價、領藥等行政流程', 1),
  ('wheelchair_route_support', '輪椅動線協助', '院內無障礙動線與輪椅移動協助', 2),
  ('dementia_communication', '失智溝通應對', '重複詢問、情緒安撫與走失預防的溝通方式', 3),
  ('post_procedure_discharge_protocol', '術後離院流程', '依院方規定協助辦理離院與安全返家', 4)
on conflict (code) do nothing;

create table if not exists staff_capability_verifications (
  id            bigint generated by default as identity primary key,
  companion_id  bigint not null references companions(id) on delete cascade,
  capability_code text not null references staff_capabilities(code),
  status        text not null default 'verified',
  verified_at   timestamptz not null default now(),
  expires_at    date,
  verified_by_admin_id bigint,
  note          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint scv_status_chk check (status in ('verified', 'expired', 'suspended')),
  constraint scv_note_len_chk check (note is null or char_length(note) <= 200),
  unique (companion_id, capability_code)
);
create index if not exists idx_scv_companion on staff_capability_verifications(companion_id, status);

-- ── 4. 週期性可服務時段（兼職為主）────────────────────────
-- 既有的 companion_availability 是「單日時段」，兩者並存：
-- 這裡是週期性規則，用於媒合篩選；單日仍可另外勾選。
create table if not exists staff_availability_rules (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  weekday      smallint not null,          -- 0=週日 … 6=週六（台灣時間）
  start_time   time not null,
  end_time     time not null,
  region       text,                        -- 留空代表沿用本人所有服務區
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint sar_weekday_chk check (weekday between 0 and 6),
  constraint sar_time_chk check (end_time > start_time)
);
create index if not exists idx_sar_companion on staff_availability_rules(companion_id, active);
create index if not exists idx_sar_weekday on staff_availability_rules(weekday) where active;

-- ── 5. 請假／暫停接案 ──────────────────────────────────────
create table if not exists staff_time_off_requests (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  request_type text not null,
  start_date   date not null,
  end_date     date not null,
  reason_code  text not null,
  note         text,
  status       text not null default 'submitted',
  reviewed_by_admin_id bigint,
  reviewed_at  timestamptz,
  review_note  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint sto_type_chk check (request_type in ('leave', 'unavailable')),
  constraint sto_status_chk check (status in ('submitted', 'approved', 'rejected', 'cancelled')),
  constraint sto_period_chk check (end_date >= start_date),
  constraint sto_note_len_chk check (note is null or char_length(note) <= 200),
  constraint sto_review_note_len_chk check (review_note is null or char_length(review_note) <= 200)
);
create index if not exists idx_sto_companion on staff_time_off_requests(companion_id, status);
create index if not exists idx_sto_period on staff_time_off_requests(start_date, end_date) where status = 'approved';

-- ── 6. 兼職服務邀請 ────────────────────────────────────────
-- ⚠️ proposal 不是 Assignment、不是 Order、不是薪資資料。
-- 只有 accepted 之後才會設定 care_bookings.companion_id（＝正式指派）。
create table if not exists care_dispatch_proposals (
  id           bigint generated by default as identity primary key,
  booking_id   bigint not null references care_bookings(id) on delete restrict,
  care_case_id bigint references care_cases(id),
  companion_id bigint not null references companions(id) on delete restrict,
  status       text not null default 'proposed',
  expires_at   timestamptz not null,
  responded_at timestamptz,
  decline_reason_code text,
  decline_note text,
  created_by_admin_id bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint cdp_status_chk check (status in
    ('proposed', 'accepted', 'declined', 'expired', 'cancelled')),
  constraint cdp_decline_note_len_chk check (decline_note is null or char_length(decline_note) <= 200),
  constraint cdp_decline_reason_chk check (status <> 'declined' or decline_reason_code is not null)
);
create index if not exists idx_cdp_companion on care_dispatch_proposals(companion_id, status);
create index if not exists idx_cdp_booking on care_dispatch_proposals(booking_id, status);

-- 同一筆服務最多只能有一個 accepted proposal
create unique index if not exists uniq_cdp_accepted_per_booking
  on care_dispatch_proposals(booking_id) where status = 'accepted';
-- 同一人同一筆服務同時只能有一個未回覆的邀請
create unique index if not exists uniq_cdp_open_per_pair
  on care_dispatch_proposals(booking_id, companion_id) where status = 'proposed';

-- ── 7. 接受邀請：資料庫端的並發保護 ───────────────────────
-- 兩位兼職同時按下「接受」時，靠這支函式的 row lock 保證最多一個成功。
-- 不能只靠前端 disabled 按鈕，也不能靠應用層先讀後寫。
create or replace function care_accept_dispatch_proposal(
  p_proposal_id bigint, p_companion_id bigint
) returns table (ok boolean, reason text, out_booking_id bigint)
language plpgsql as $$
declare
  v_p care_dispatch_proposals%rowtype;
  v_assigned bigint;
  v_emp text;
begin
  select * into v_p from care_dispatch_proposals where id = p_proposal_id for update;
  if not found then
    return query select false, 'proposal_not_found', null::bigint; return;
  end if;
  if v_p.companion_id <> p_companion_id then
    return query select false, 'not_your_proposal', null::bigint; return;
  end if;
  if v_p.status <> 'proposed' then
    return query select false, 'proposal_not_open', null::bigint; return;
  end if;
  if v_p.expires_at <= now() then
    update care_dispatch_proposals set status = 'expired', updated_at = now()
      where id = p_proposal_id;
    return query select false, 'proposal_expired', null::bigint; return;
  end if;

  -- 僱用條件必須仍然有效
  select employment_type into v_emp from staff_employment_terms
    where companion_id = p_companion_id and status = 'active'
      and effective_from <= current_date
      and (effective_to is null or effective_to >= current_date)
    limit 1;
  if v_emp is null then
    return query select false, 'employment_inactive', null::bigint; return;
  end if;

  -- 鎖住服務列，確認還沒有人被指派
  select companion_id into v_assigned from care_bookings
    where id = v_p.booking_id for update;
  if v_assigned is not null then
    update care_dispatch_proposals set status = 'cancelled', updated_at = now()
      where id = p_proposal_id;
    return query select false, 'already_assigned', null::bigint; return;
  end if;

  -- 正式指派：設定 companion_id 就是既有的 Assignment 語意
  update care_bookings
    set companion_id = p_companion_id, status = '已派工', updated_at = now()
    where id = v_p.booking_id;

  update care_dispatch_proposals
    set status = 'accepted', responded_at = now(), updated_at = now()
    where id = p_proposal_id;

  -- 同一筆服務的其他未回覆邀請一併撤回，讀取範圍立即收回
  update care_dispatch_proposals
    set status = 'cancelled', updated_at = now()
    where booking_id = v_p.booking_id and id <> p_proposal_id and status = 'proposed';

  return query select true, 'ok', v_p.booking_id;
end $$;

-- ── 8. 狀態機守衛 ──────────────────────────────────────────
create or replace function care_guard_proposal() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'proposed' and new.status in ('accepted','declined','expired','cancelled'))
    ) then
      raise exception 'care_dispatch_proposal: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists trg_cdp_guard on care_dispatch_proposals;
create trigger trg_cdp_guard before update on care_dispatch_proposals
  for each row execute function care_guard_proposal();

create or replace function care_guard_time_off() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'submitted' and new.status in ('approved','rejected','cancelled'))
    ) then
      raise exception 'staff_time_off_request: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists trg_sto_guard on staff_time_off_requests;
create trigger trg_sto_guard before update on staff_time_off_requests
  for each row execute function care_guard_time_off();

-- ── 9. updated_at ──────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'staff_employment_terms','staff_capability_verifications','staff_availability_rules',
    'staff_time_off_requests','care_dispatch_proposals'
  ] loop
    execute format('drop trigger if exists trg_%s_touch on %I', t, t);
    execute format(
      'create trigger trg_%s_touch before update on %I for each row execute function care_touch_updated_at()',
      t, t);
  end loop;
end $$;

-- ── 10. Backfill：從既有欄位補資料 ────────────────────────
-- 僱用型態：從 companions.employment_type 帶入。
-- 舊值只有 fulltime / parttime 兩種，對應明確，不是猜測。
-- 若日後出現無法對應的值，會留在 needs_review 由人工補。
insert into staff_employment_terms (companion_id, employment_type, status, effective_from, note)
select c.id,
       case c.employment_type when 'fulltime' then 'full_time' else 'part_time' end,
       case when c.status = 'suspended' then 'paused' else 'active' end,
       coalesce(c.created_at::date, current_date),
       '由 companions.employment_type 自動帶入（Sprint C backfill）'
from companions c
where c.employment_type in ('fulltime', 'parttime')
  and not exists (select 1 from staff_employment_terms t where t.companion_id = c.id);

-- 服務區域：從 companions.service_areas jsonb 展開
insert into staff_service_regions (companion_id, region)
select c.id, r.value #>> '{}'
from companions c, lateral jsonb_array_elements(coalesce(c.service_areas, '[]'::jsonb)) as r(value)
where jsonb_typeof(coalesce(c.service_areas, '[]'::jsonb)) = 'array'
on conflict (companion_id, region) do nothing;

-- ⚠️ 未帶入的情況需要人工處理：
--   select id, name, employment_type from companions
--   where id not in (select companion_id from staff_employment_terms);

-- ── 11. RLS：預設全部拒絕 ─────────────────────────────────
-- 與 Sprint B/D 相同：後台與陪診員端都走 service_role，
-- RLS 是縱深防禦，授權的實際強制點在 Service 層與 Route Handler。
do $$
declare t text;
begin
  foreach t in array array[
    'staff_employment_terms','staff_service_regions','staff_capabilities',
    'staff_capability_verifications','staff_availability_rules',
    'staff_time_off_requests','care_dispatch_proposals'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force row level security', t);
    execute format('revoke all on %I from anon, authenticated', t);
  end loop;
end $$;

-- 完成 ✓
