-- ===========================================================
-- 陪診員：自助註冊、證件資料、服務過程記錄
-- 需先執行 companion_care_schema.sql 與 companion_settlement.sql
-- 在 Supabase SQL Editor 執行此檔案即可
-- ===========================================================

-- ── 1. 私有儲存空間（敏感文件絕不可公開）────────────────────
-- companion-docs：身分證、存摺、學歷證明
-- care-records  ：服務過程照片（可能含醫院場景，一律不公開）
insert into storage.buckets (id, name, public)
values ('companion-docs', 'companion-docs', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('care-records', 'care-records', false)
on conflict (id) do nothing;

-- ── 2. 陪診員完整資料 ──────────────────────────────────────
alter table companions add column if not exists id_number          text;  -- 身分證字號（僅超級管理員可見）
alter table companions add column if not exists birthday           date;
alter table companions add column if not exists address            text;
alter table companions add column if not exists education          text;  -- 最高學歷
alter table companions add column if not exists school             text;
alter table companions add column if not exists experience         text;  -- 相關經歷
alter table companions add column if not exists emergency_contact  text;
alter table companions add column if not exists emergency_phone    text;
alter table companions add column if not exists emergency_relation text;
-- 匯款帳戶（結算用）
alter table companions add column if not exists bank_name          text;
alter table companions add column if not exists bank_branch        text;
alter table companions add column if not exists bank_account       text;
alter table companions add column if not exists bank_account_name  text;
-- 證件檔案（存 storage 路徑，非公開網址）
alter table companions add column if not exists doc_id_front       text;  -- 身分證正面
alter table companions add column if not exists doc_id_back        text;  -- 身分證反面
alter table companions add column if not exists doc_bankbook       text;  -- 存摺封面
alter table companions add column if not exists doc_education      text;  -- 學歷證明
alter table companions add column if not exists doc_certificate    text;  -- 證照
-- 審核流程
alter table companions add column if not exists profile_submitted_at timestamptz; -- 送出審核時間
alter table companions add column if not exists reviewed_at        timestamptz;
alter table companions add column if not exists reviewed_by        text;
alter table companions add column if not exists reject_reason      text;
alter table companions add column if not exists consent_at         timestamptz; -- 個資蒐集同意時間

-- ── 3. 服務過程記錄（時間軸）────────────────────────────────
create table if not exists care_booking_events (
  id           bigint generated by default as identity primary key,
  booking_id   bigint not null references care_bookings(id) on delete cascade,
  companion_id bigint references companions(id),
  event_type   text not null,
  -- accepted 接受派工 / declined 婉拒 / contacted 行前電話確認 /
  -- met 已會合 / progress 服務進度 / doctor_note 醫師重要提醒 / completed 服務完成
  note         text,
  photos       jsonb default '[]'::jsonb,   -- storage 路徑陣列（私有）
  created_at   timestamptz default now()
);
create index if not exists idx_care_events_booking on care_booking_events(booking_id);
create index if not exists idx_care_events_created on care_booking_events(created_at);

-- ── 4. 預約單上的流程快取欄位（列表快速顯示用）──────────────
alter table care_bookings add column if not exists accepted_at          timestamptz;
alter table care_bookings add column if not exists declined_at          timestamptz;
alter table care_bookings add column if not exists decline_reason       text;
alter table care_bookings add column if not exists contact_confirmed_at timestamptz;
alter table care_bookings add column if not exists met_at               timestamptz;
alter table care_bookings add column if not exists doctor_notes         text;
alter table care_bookings add column if not exists completed_at         timestamptz;

-- 完成 ✓
-- 注意：companion-docs 與 care-records 為「私有」bucket，
--       系統一律以有效期 5 分鐘的簽名網址讀取，不會產生公開連結。
