-- ===========================================================
-- 陪診服務 完整資料庫建置（4 個 migration 合併）
-- 直接整份貼到 Supabase SQL Editor 執行即可
-- 全部可重複執行，已存在的不會出錯
-- ===========================================================

-- ╔══ 1/4 companion_care_schema.sql ═══════════════════════╗
-- ===========================================================
-- 陪診服務：方案、預約、陪診員、可服務時段
-- 在 Supabase SQL Editor 執行此檔案即可
-- ===========================================================

-- ── 1. 陪診方案 ────────────────────────────────────────────
create table if not exists care_services (
  id          bigint generated by default as identity primary key,
  code        text unique not null,
  name        text not null,
  hours_label text,                       -- 例：約 4 小時（半日）
  price       integer not null,
  member_price integer,                   -- 會員優惠價（可為 null）
  summary     text,
  features    jsonb default '[]'::jsonb,  -- 服務內容條列
  suitable    text,                       -- 適合情境
  sort_order  integer default 0,
  is_active   boolean default true,
  created_at  timestamptz default now()
);

insert into care_services (code, name, hours_label, price, member_price, summary, suitable, features, sort_order)
values
('basic', '輕鬆陪診', '約 2 小時', 1000, 900,
 '單純門診回診、拿藥的短時間陪同',
 '慢性病固定回診、拿慢性處方箋、報告解讀回診',
 '["現場會合、協助報到與候診","診間外等候、看診後重點筆記","協助批價、領藥、確認用藥時間","服務結束後 LINE 回報家屬"]'::jsonb, 1),
('standard', '標準陪診（半日）', '約 4 小時', 1800, 1650,
 '最常見方案，含檢查與等待時間',
 '初診、需要抽血/X光等檢查、看診＋檢查同日完成',
 '["醫院大廳會合，全程陪同"," 協助掛號報到、跑檢查室動線","候診陪伴、協助與醫護溝通(不代做醫療決定)","看診重點筆記＋用藥說明整理","協助批價、領藥","服務中與服務後即時回報家屬"]'::jsonb, 2),
('full', '安心全日', '約 8 小時', 3200, 2950,
 '檢查項目多、需要長時間等待的完整陪同',
 '全身健檢、多科別同日看診、日間手術、住院當日陪同',
 '["全日陪同，含中午用餐協助","多科別／多檢查室完整動線陪同","協助辦理住院或日間手術報到","看診與檢查重點完整整理","協助批價、領藥、預約下次回診","全程分段回報家屬"]'::jsonb, 3),
('postop', '術後／麻醉離院陪同', '約 3 小時', 1500, 1400,
 '無痛檢查、日間手術後依規定需人陪同離院',
 '無痛胃鏡／大腸鏡、日間手術、麻醉後不可自行離院',
 '["術前報到陪同","麻醉／術後恢復室外等候","依院方規定陪同辦理離院","協助叫車、安全送返住家或指定地點","返家後 LINE 回報家屬"]'::jsonb, 4)
on conflict (code) do nothing;

-- ── 2. 陪診員 ──────────────────────────────────────────────
create table if not exists companions (
  id              bigint generated by default as identity primary key,
  name            text not null,
  phone           text not null unique,          -- 同時作為登入帳號
  email           text,
  password_hash   text not null,
  gender          text,                          -- female / male / na（部分長輩偏好同性陪診）
  employment_type text default 'parttime',       -- fulltime / parttime
  service_areas   jsonb default '[]'::jsonb,     -- 可服務縣市
  certifications  text,                          -- 證照：照服員、CPR、BLS…
  bio             text,
  status          text default 'pending',        -- pending 待審核 / active 啟用 / suspended 停用
  completed_count integer default 0,
  admin_note      text,
  created_at      timestamptz default now()
);
create index if not exists idx_companions_status on companions(status);

-- ── 3. 陪診員可服務時段 ────────────────────────────────────
create table if not exists companion_availability (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  date         date not null,
  time_slot    text not null,                    -- morning / afternoon / allday
  created_at   timestamptz default now(),
  unique (companion_id, date, time_slot)
);
create index if not exists idx_avail_date on companion_availability(date);

-- ── 4. 陪診預約 ────────────────────────────────────────────
create table if not exists care_bookings (
  id             bigint generated by default as identity primary key,
  booking_no     text unique not null,
  -- 方案（下單當下快照，日後改價不影響既有預約）
  service_code   text,
  service_name   text,
  price          integer,
  -- 就診人
  patient_name   text not null,
  patient_age    text,
  patient_gender text,
  mobility       text,          -- walk 自行行走 / assist 需攙扶 / wheelchair 輪椅
  -- 聯絡人（多半是子女）
  contact_name   text not null,
  contact_phone  text not null,
  contact_line   text,
  relation       text,          -- 與就診人關係
  -- 就醫資訊
  service_date   date not null,
  time_slot      text,          -- morning / afternoon / allday
  county         text,
  hospital       text,
  department     text,
  addons         jsonb default '[]'::jsonb,   -- 加購：到府接送、代排隊等
  notes          text,
  -- 流程狀態
  status         text default '待確認',
  -- 待確認 → 待匯款 → 已付款 → 已派工 → 服務中 → 已完成 ／ 已取消
  companion_id   bigint references companions(id),
  admin_note     text,
  user_id        uuid,          -- 若為登入會員預約
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);
create index if not exists idx_care_bookings_status on care_bookings(status);
create index if not exists idx_care_bookings_date on care_bookings(service_date);
create index if not exists idx_care_bookings_companion on care_bookings(companion_id);

-- 完成 ✓
-- 建立第一位陪診員：請到後台「陪診員管理」新增（密碼會自動雜湊）。

-- ── 5. 後台角色：陪診客服 ──────────────────────────────────
-- 讓專責處理陪診預約的人員只看得到陪診相關頁面
insert into admin_roles (role_key, role_name, permissions_json)
select 'care_staff', '陪診客服', '["care.view"]'::jsonb
where not exists (select 1 from admin_roles where role_key = 'care_staff');

-- ╔══ 2/4 companion_settlement.sql ════════════════════════╗
-- ===========================================================
-- 陪診服務：收入結算欄位
-- 需先執行 companion_care_schema.sql
-- 在 Supabase SQL Editor 執行此檔案即可
-- ===========================================================

-- 方案預設的陪診員報酬（平台約抽 40%，可自行調整）
alter table care_services add column if not exists companion_fee integer;

update care_services set companion_fee = 600  where code = 'basic'    and companion_fee is null;
update care_services set companion_fee = 1100 where code = 'standard' and companion_fee is null;
update care_services set companion_fee = 2000 where code = 'full'     and companion_fee is null;
update care_services set companion_fee = 900  where code = 'postop'   and companion_fee is null;

-- 每筆預約的結算欄位
alter table care_bookings add column if not exists companion_fee   integer;      -- 該筆的陪診員報酬（可個別調整）
alter table care_bookings add column if not exists extra_fee       integer default 0; -- 額外收費（超時、加購等）
alter table care_bookings add column if not exists settled_at      timestamptz;  -- 結算時間（null = 未結算）
alter table care_bookings add column if not exists settlement_note text;

create index if not exists idx_care_bookings_settled on care_bookings(settled_at);

-- 既有已完成但尚未帶入報酬的預約，補上方案預設值
update care_bookings b
set companion_fee = s.companion_fee
from care_services s
where b.service_code = s.code and b.companion_fee is null;

-- 完成 ✓
-- 想調整拆帳比例：直接改 care_services.companion_fee 即可（之後的新預約會沿用）。

-- ╔══ 3/4 companion_profile_records.sql ═══════════════════╗
-- ===========================================================
-- 陪診員：自助註冊、證件資料、服務過程記錄
-- 需先執行 companion_care_schema.sql 與 companion_settlement.sql
-- 在 Supabase SQL Editor 執行此檔案即可
-- ===========================================================

-- ── 1. 私有儲存空間（敏感文件絕不可公開）────────────────────
-- companion-docs：身分證、存摺、學歷證明
-- care-records  ：服務過程照片（可能含醫院場景，一律不公開）
insert into storage.buckets (id, name, public)
values ('companion-docs', 'companion-docs', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('care-records', 'care-records', false)
on conflict (id) do nothing;

-- ── 2. 陪診員完整資料 ──────────────────────────────────────
alter table companions add column if not exists id_number          text;  -- 身分證字號（僅超級管理員可見）
alter table companions add column if not exists birthday           date;
alter table companions add column if not exists address            text;
alter table companions add column if not exists education          text;  -- 最高學歷
alter table companions add column if not exists school             text;
alter table companions add column if not exists experience         text;  -- 相關經歷
alter table companions add column if not exists emergency_contact  text;
alter table companions add column if not exists emergency_phone    text;
alter table companions add column if not exists emergency_relation text;
-- 匯款帳戶（結算用）
alter table companions add column if not exists bank_name          text;
alter table companions add column if not exists bank_branch        text;
alter table companions add column if not exists bank_account       text;
alter table companions add column if not exists bank_account_name  text;
-- 證件檔案（存 storage 路徑，非公開網址）
alter table companions add column if not exists doc_id_front       text;  -- 身分證正面
alter table companions add column if not exists doc_id_back        text;  -- 身分證反面
alter table companions add column if not exists doc_bankbook       text;  -- 存摺封面
alter table companions add column if not exists doc_education      text;  -- 學歷證明
alter table companions add column if not exists doc_certificate    text;  -- 證照
-- 審核流程
alter table companions add column if not exists profile_submitted_at timestamptz; -- 送出審核時間
alter table companions add column if not exists reviewed_at        timestamptz;
alter table companions add column if not exists reviewed_by        text;
alter table companions add column if not exists reject_reason      text;
alter table companions add column if not exists consent_at         timestamptz; -- 個資蒐集同意時間

-- ── 3. 服務過程記錄（時間軸）────────────────────────────────
create table if not exists care_booking_events (
  id           bigint generated by default as identity primary key,
  booking_id   bigint not null references care_bookings(id) on delete cascade,
  companion_id bigint references companions(id),
  event_type   text not null,
  -- accepted 接受派工 / declined 婉拒 / contacted 行前電話確認 /
  -- met 已會合 / progress 服務進度 / doctor_note 醫師重要提醒 / completed 服務完成
  note         text,
  photos       jsonb default '[]'::jsonb,   -- storage 路徑陣列（私有）
  created_at   timestamptz default now()
);
create index if not exists idx_care_events_booking on care_booking_events(booking_id);
create index if not exists idx_care_events_created on care_booking_events(created_at);

-- ── 4. 預約單上的流程快取欄位（列表快速顯示用）──────────────
alter table care_bookings add column if not exists accepted_at          timestamptz;
alter table care_bookings add column if not exists declined_at          timestamptz;
alter table care_bookings add column if not exists decline_reason       text;
alter table care_bookings add column if not exists contact_confirmed_at timestamptz;
alter table care_bookings add column if not exists met_at               timestamptz;
alter table care_bookings add column if not exists doctor_notes         text;
alter table care_bookings add column if not exists completed_at         timestamptz;

-- 完成 ✓
-- 注意：companion-docs 與 care-records 為「私有」bucket，
--       系統一律以有效期 5 分鐘的簽名網址讀取，不會產生公開連結。

-- ╔══ 4/4 companion_pickup_addons.sql ═════════════════════╗
-- ===========================================================
-- 陪診服務：到府接送地址與加購費用
-- 需先執行 companion_care_schema.sql / companion_settlement.sql
-- 在 Supabase SQL Editor 執行此檔案即可
-- ===========================================================

-- 接送資訊（客服與客戶確認後填寫）
alter table care_bookings add column if not exists pickup_address text;  -- 接送詳細地址
alter table care_bookings add column if not exists pickup_time    text;  -- 到府時間，例：08:00
alter table care_bookings add column if not exists pickup_note    text;  -- 補充：大樓警衛、電梯、需上樓攙扶…

-- 加購費用
alter table care_bookings add column if not exists addon_fee           integer default 0; -- 客戶加付金額（應收）
alter table care_bookings add column if not exists addon_companion_fee integer default 0; -- 加購部分給陪診員的報酬

-- 完成 ✓
-- 營收 = price + addon_fee + extra_fee
-- 陪診員報酬 = companion_fee + addon_companion_fee
