-- ===========================================================
-- 下單漏斗事件：記錄「加入購物車 / 送出點擊 / 送出失敗 / 下單成功」
-- 搭配既有 page_views（商品瀏覽、進入結帳）即可還原完整漏斗
-- 在 Supabase SQL Editor 執行此檔案即可
-- ===========================================================

create table if not exists funnel_events (
  id          bigint generated by default as identity primary key,
  event       text not null,               -- add_to_cart / submit_click / submit_fail / order_success
  visitor_id  text,                        -- 對應 page_views 的訪客識別（cookie）
  user_id     uuid,                         -- 會員 id（可為 null）
  path        text,
  meta        jsonb,                        -- 例如 { reason: 'store' } 或 { order_no: '...' }
  created_at  timestamptz not null default now()
);

create index if not exists idx_funnel_events_created on funnel_events(created_at);
create index if not exists idx_funnel_events_event_created on funnel_events(event, created_at);
create index if not exists idx_funnel_events_visitor on funnel_events(visitor_id);

-- 完成 ✓（表未建立前，前台埋點與後台漏斗頁都會容錯為「無資料」，不會報錯）
