-- ═══════════════════════════════════════════════════════════
-- 商品分類（逛街用）
--
-- 冪等，可重複執行。
--
-- 為什麼不是改掉 health_categories
-- ────────────────────────────────
-- health_categories 是「健康訴求」分類（骨關節、心血管、助眠…），
-- 它同時被這些地方用著：
--   • health_articles.category_slug —— 每篇健康知識屬於哪個訴求
--   • 文章頁的推薦商品、商品頁的延伸閱讀
--   • 健康自測 / 睡眠自測的結果頁
-- 把它換成商品型態分類，上面這些會全部失去依據：一篇講心血管的文章
-- 要推薦商品時，「營養支持」這種粒度是推不出東西的。
--
-- 所以新增一套平行的分類：前台購物動線改用這一套，健康訴求那套留給
-- 文章與自測繼續用。一件商品可以同時有兩種分類，彼此不衝突。
-- ═══════════════════════════════════════════════════════════

create table if not exists shop_categories (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  name        text not null,
  emoji       text not null default '',
  description text not null default '',
  sort_order  int  not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),

  constraint shop_category_slug_chk check (slug ~ '^[a-z][a-z-]*[a-z]$'),
  constraint shop_category_name_len_chk check (char_length(name) between 1 and 20)
);

create index if not exists idx_shop_categories_active
  on shop_categories(sort_order) where is_active = true;


-- ── 商品 ↔ 分類（多對多）────────────────────────────────
-- 一件商品可以掛多個分類：即食阿膠糕既是養生膏方也是傳統滋補。
create table if not exists product_shop_category_relations (
  product_id       bigint not null references products(id) on delete cascade,
  shop_category_id bigint not null references shop_categories(id) on delete cascade,
  primary key (product_id, shop_category_id)
);

-- 分類頁是「給我這個分類的所有商品」，所以要能從分類反查商品
create index if not exists idx_pscr_category
  on product_shop_category_relations(shop_category_id);


-- ── 九個分類 ────────────────────────────────────────────
-- 與 lib/shopCategories.ts 的 SHOP_CATEGORIES 一致。
-- 只插入還不存在的 slug；名稱、說明、排序之後可以在後台改，重跑這個
-- 檔案不會把改過的內容蓋回去。
insert into shop_categories (slug, name, emoji, description, sort_order)
values
  ('nutrition',      '營養支持',     '💊', '每日補充的營養素與機能性食用油，膠囊、軟膠囊、錠劑與粉包。', 10),
  ('tea',            '養身茶飲',     '🍵', '天天喝得下去的茶包與沖泡飲品，溫和、順口、好持續。',         20),
  ('snacks',         '健康零食',     '🥜', '嘴饞時的替代選擇：堅果、果乾與少負擔的點心。',               30),
  ('patch-care',     '個護敷貼',     '🩹', '貼上就走的日常照護，與隨身清潔保養用品。',                   40),
  ('foot-bath',      '足浴香囊',     '👣', '睡前泡腳包與隨身香囊，用氣味與溫度把一天收起來。',           50),
  ('herbal-paste',   '養生膏方',     '🍯', '一匙一匙吃的膏方，傳統做法、慢慢調養。',                     60),
  ('tonic',          '傳統滋補',     '🍲', '藥膳、燉品與經典滋補食材，家裡廚房就能用。',                 70),
  ('topical-herbal', '外用草本保養', '🌿', '抹在身上的草本配方：按摩油、舒緩霜與噴霧。',                 80),
  ('home-living',    '居家生活',     '🏠', '會陪你很久的日常器物：鍋具、燈具與廚房小件。',               90)
on conflict (slug) do nothing;


-- ═══════════════════════════════════════════════════════════
-- 執行完之後
-- ═══════════════════════════════════════════════════════════
-- 現有商品都還沒有商品分類，分類頁會是空的。
-- 請到後台 →「商品管理」→「批次指派分類」，畫面會依商品名稱自動
-- 建議分類，逐一確認即可。沒有指派分類的商品仍然會出現在 /shop 的
-- 「全部商品」，不會從賣場消失。
--
-- 之後新增商品時，商品分類是必選的（可以選多個）。
-- ═══════════════════════════════════════════════════════════
