-- ═══════════════════════════════════════════════════════════
-- 前台彈窗（可在後台開關與新增）
--
-- 冪等，可重複執行。
--
-- 原本彈窗的設定寫死在 lib/presale/camelliaOil.ts，要改內容或關掉
-- 都得改程式碼重新部署。這張表把設定搬進資料庫，後台就能自己管理，
-- 也能為不同商品各建一個。
-- ═══════════════════════════════════════════════════════════

create table if not exists site_popups (
  id            bigint generated by default as identity primary key,

  -- ── 內容 ──
  name          text not null,               -- 後台自己看的名稱
  badge_text    text,                        -- 小標籤，例：🌿 預售中
  title         text not null,
  body          text,
  price_text    text,                        -- 例：NT$1,350 / 500ml
  image_url     text,                        -- 留空則用 product_slug 的封面
  cta_text      text not null default '看看詳情',
  link_path     text not null,               -- 站內路徑，必須以 / 開頭

  -- ── 關聯商品（可選）──
  -- 填了就會自動抓封面圖；也讓後台知道這個彈窗在推哪個商品
  product_slug  text,

  -- ── 顯示規則 ──
  is_active     boolean not null default false,
  priority      int not null default 0,      -- 數字大的優先；同時只顯示一個
  delay_ms      int not null default 800,
  auto_close_ms int not null default 5000,   -- 0 = 不自動關閉
  cooldown_hours int not null default 12,
  starts_at     date,                        -- 空 = 不限
  ends_at       date,                        -- 空 = 不限

  -- 只在這些路徑顯示（空陣列 = 全站）
  include_paths jsonb not null default '[]'::jsonb,
  -- 這些路徑不顯示（結帳流程等）
  exclude_paths jsonb not null default '["/cart","/checkout","/order-success"]'::jsonb,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  created_by_admin_id bigint,

  constraint site_popup_link_chk check (link_path like '/%' and link_path not like '//%'),
  constraint site_popup_title_len_chk check (char_length(title) between 1 and 40),
  constraint site_popup_body_len_chk check (body is null or char_length(body) <= 120),
  constraint site_popup_cta_len_chk check (char_length(cta_text) between 1 and 20),
  constraint site_popup_badge_len_chk check (badge_text is null or char_length(badge_text) <= 30),
  constraint site_popup_price_len_chk check (price_text is null or char_length(price_text) <= 30),
  constraint site_popup_delay_chk check (delay_ms between 0 and 60000),
  constraint site_popup_autoclose_chk check (auto_close_ms between 0 and 120000),
  constraint site_popup_cooldown_chk check (cooldown_hours between 0 and 720),
  constraint site_popup_window_chk check (starts_at is null or ends_at is null or starts_at <= ends_at)
);

create index if not exists idx_site_popups_active
  on site_popups(is_active, priority desc) where is_active = true;


-- ── 連結必須是站內路徑，且不可帶參數 ─────────────────────
-- query string 會進到伺服器 log 與 analytics；深層頁面本來就會
-- 自己再做一次授權檢查，連結不需要（也不該）夾帶任何東西。
create or replace function site_popup_guard() returns trigger
language plpgsql as $$
begin
  if position('?' in new.link_path) > 0 or position('#' in new.link_path) > 0 then
    raise exception '彈窗連結不可帶參數';
  end if;
  if new.image_url is not null and new.image_url !~ '^https?://' then
    raise exception '圖片網址格式不正確';
  end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists trg_site_popup_guard on site_popups;
create trigger trg_site_popup_guard before insert or update on site_popups
  for each row execute function site_popup_guard();


-- ── 把原本寫死的野生茶籽油彈窗搬進來 ─────────────────────
-- 只在完全沒有資料時建立，重跑不會覆蓋後台改過的內容。
insert into site_popups (
  name, badge_text, title, body, price_text, cta_text, link_path,
  product_slug, is_active, priority, ends_at
)
select
  '野生茶籽油預售',
  '🌿 預售中 · 今年只有這一批',
  '野生茶籽油',
  '山上現在還在採，果實自然裂開才摘。預計 10 月出油後直接寄給您。',
  'NT$1,350 / 500ml',
  '看看這批油',
  '/camellia-oil',
  'wild-camellia-oil',
  true,
  100,
  '2026-10-31'
where not exists (select 1 from site_popups);


-- ── RLS ────────────────────────────────────────────────────
-- 與其他表相同：伺服器走 service_role，RLS 是縱深防禦。
-- 公開端點只回傳「已啟用且在期間內」的彈窗，且欄位固定。
alter table site_popups enable row level security;
alter table site_popups force row level security;
revoke all on site_popups from anon, authenticated;

-- 完成 ✓
