-- ═══════════════════════════════════════════════════════════
-- Sprint C ＋ Sprint D 合併 migration
--
-- 依正確順序合併，可一次貼進 Supabase SQL Editor 執行。
-- 內容與 care_staffing_schema.sql、care_fulfilment_schema.sql
-- 完全相同，兩份皆冪等，重複執行不會出錯。
--
--   1. care_staffing_schema.sql    ← Sprint C（人力、班表、媒合）
--   2. care_fulfilment_schema.sql  ← Sprint D（履約、小結、結算）
--
-- 前置：companion_care_schema.sql 與 care_operations_schema.sql
--       必須已經執行過（本檔會 FK 到 companions / care_bookings / care_cases）。
-- ═══════════════════════════════════════════════════════════


-- ╔═════════════════════════════════════════════════════════╗
-- ║  第 1 段：Sprint C —— 陪診人力、班表與人工媒合          ║
-- ╚═════════════════════════════════════════════════════════╝

-- ===========================================================
-- Sprint C：陪診員管理、人工媒合與班表
-- 在 Supabase SQL Editor 執行。可重複執行。
--
-- 對應關係（本專案沒有規格書假設的那套命名）：
--   StaffProfile  → companions
--   Assignment    → care_bookings.companion_id（設值即為正式指派）
--   ServiceTask   → 沒有獨立表，由 care_bookings.status 承擔
--   Staff Portal  → /companion
--
-- 本檔案「正規化並延伸」既有欄位，不刪除它們：
--   companions.employment_type → staff_employment_terms（版本化、有期間）
--   companions.service_areas   → staff_service_regions（正規化多對多）
--   companion_availability     → 保留（單日時段），另加週期性規則
--
-- 需先執行 companion_care_schema.sql 與 care_operations_schema.sql
-- ===========================================================

-- ── 0. 案件 → 正式服務的橋接 ──────────────────────────────
-- Sprint B 的 care_cases 沒有連到 care_bookings，因此無從派工。
-- 這裡補一個唯一關聯：媒合前先把案件「實體化」成一筆正式服務。
alter table care_cases add column if not exists booking_id bigint references care_bookings(id);
create unique index if not exists uniq_care_case_booking
  on care_cases(booking_id) where booking_id is not null;

-- ── 1. 僱用型態（版本化）──────────────────────────────────
create table if not exists staff_employment_terms (
  id             bigint generated by default as identity primary key,
  companion_id   bigint not null references companions(id) on delete cascade,
  employment_type text not null,
  status         text not null default 'active',
  effective_from date not null,
  effective_to   date,
  note           text,
  created_by_admin_id bigint,
  ended_by_admin_id   bigint,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint set_type_chk check (employment_type in ('full_time', 'part_time')),
  constraint set_status_chk check (status in ('active', 'paused', 'ended')),
  constraint set_period_chk check (effective_to is null or effective_to >= effective_from),
  constraint set_note_len_chk check (note is null or char_length(note) <= 200)
);
create index if not exists idx_set_companion on staff_employment_terms(companion_id, status);

-- 同一人同時只能有一筆未結束的僱用條件
create unique index if not exists uniq_set_open_per_companion
  on staff_employment_terms(companion_id) where status <> 'ended';

-- ── 2. 服務區域（正規化）──────────────────────────────────
create table if not exists staff_service_regions (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  region       text not null,
  created_by_admin_id bigint,
  created_at   timestamptz not null default now(),
  unique (companion_id, region)
);
create index if not exists idx_ssr_region on staff_service_regions(region);

-- ── 3. 能力與驗證 ──────────────────────────────────────────
-- ⚠️ 這些不是醫療執照，也不是醫療資格，不得用於宣稱醫療專業。
create table if not exists staff_capabilities (
  code        text primary key,
  label       text not null,
  description text,
  sort_order  integer default 0
);

insert into staff_capabilities (code, label, description, sort_order) values
  ('general_outpatient_flow', '一般門診流程協助', '報到、候診、批價、領藥等行政流程', 1),
  ('wheelchair_route_support', '輪椅動線協助', '院內無障礙動線與輪椅移動協助', 2),
  ('dementia_communication', '失智溝通應對', '重複詢問、情緒安撫與走失預防的溝通方式', 3),
  ('post_procedure_discharge_protocol', '術後離院流程', '依院方規定協助辦理離院與安全返家', 4)
on conflict (code) do nothing;

create table if not exists staff_capability_verifications (
  id            bigint generated by default as identity primary key,
  companion_id  bigint not null references companions(id) on delete cascade,
  capability_code text not null references staff_capabilities(code),
  status        text not null default 'verified',
  verified_at   timestamptz not null default now(),
  expires_at    date,
  verified_by_admin_id bigint,
  note          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint scv_status_chk check (status in ('verified', 'expired', 'suspended')),
  constraint scv_note_len_chk check (note is null or char_length(note) <= 200),
  unique (companion_id, capability_code)
);
create index if not exists idx_scv_companion on staff_capability_verifications(companion_id, status);

-- ── 4. 週期性可服務時段（兼職為主）────────────────────────
-- 既有的 companion_availability 是「單日時段」，兩者並存：
-- 這裡是週期性規則，用於媒合篩選；單日仍可另外勾選。
create table if not exists staff_availability_rules (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  weekday      smallint not null,          -- 0=週日 … 6=週六（台灣時間）
  start_time   time not null,
  end_time     time not null,
  region       text,                        -- 留空代表沿用本人所有服務區
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint sar_weekday_chk check (weekday between 0 and 6),
  constraint sar_time_chk check (end_time > start_time)
);
create index if not exists idx_sar_companion on staff_availability_rules(companion_id, active);
create index if not exists idx_sar_weekday on staff_availability_rules(weekday) where active;

-- ── 5. 請假／暫停接案 ──────────────────────────────────────
create table if not exists staff_time_off_requests (
  id           bigint generated by default as identity primary key,
  companion_id bigint not null references companions(id) on delete cascade,
  request_type text not null,
  start_date   date not null,
  end_date     date not null,
  reason_code  text not null,
  note         text,
  status       text not null default 'submitted',
  reviewed_by_admin_id bigint,
  reviewed_at  timestamptz,
  review_note  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint sto_type_chk check (request_type in ('leave', 'unavailable')),
  constraint sto_status_chk check (status in ('submitted', 'approved', 'rejected', 'cancelled')),
  constraint sto_period_chk check (end_date >= start_date),
  constraint sto_note_len_chk check (note is null or char_length(note) <= 200),
  constraint sto_review_note_len_chk check (review_note is null or char_length(review_note) <= 200)
);
create index if not exists idx_sto_companion on staff_time_off_requests(companion_id, status);
create index if not exists idx_sto_period on staff_time_off_requests(start_date, end_date) where status = 'approved';

-- ── 6. 兼職服務邀請 ────────────────────────────────────────
-- ⚠️ proposal 不是 Assignment、不是 Order、不是薪資資料。
-- 只有 accepted 之後才會設定 care_bookings.companion_id（＝正式指派）。
create table if not exists care_dispatch_proposals (
  id           bigint generated by default as identity primary key,
  booking_id   bigint not null references care_bookings(id) on delete restrict,
  care_case_id bigint references care_cases(id),
  companion_id bigint not null references companions(id) on delete restrict,
  status       text not null default 'proposed',
  expires_at   timestamptz not null,
  responded_at timestamptz,
  decline_reason_code text,
  decline_note text,
  created_by_admin_id bigint,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint cdp_status_chk check (status in
    ('proposed', 'accepted', 'declined', 'expired', 'cancelled')),
  constraint cdp_decline_note_len_chk check (decline_note is null or char_length(decline_note) <= 200),
  constraint cdp_decline_reason_chk check (status <> 'declined' or decline_reason_code is not null)
);
create index if not exists idx_cdp_companion on care_dispatch_proposals(companion_id, status);
create index if not exists idx_cdp_booking on care_dispatch_proposals(booking_id, status);

-- 同一筆服務最多只能有一個 accepted proposal
create unique index if not exists uniq_cdp_accepted_per_booking
  on care_dispatch_proposals(booking_id) where status = 'accepted';
-- 同一人同一筆服務同時只能有一個未回覆的邀請
create unique index if not exists uniq_cdp_open_per_pair
  on care_dispatch_proposals(booking_id, companion_id) where status = 'proposed';

-- ── 7. 接受邀請：資料庫端的並發保護 ───────────────────────
-- 兩位兼職同時按下「接受」時，靠這支函式的 row lock 保證最多一個成功。
-- 不能只靠前端 disabled 按鈕，也不能靠應用層先讀後寫。
create or replace function care_accept_dispatch_proposal(
  p_proposal_id bigint, p_companion_id bigint
) returns table (ok boolean, reason text, out_booking_id bigint)
language plpgsql as $$
declare
  v_p care_dispatch_proposals%rowtype;
  v_assigned bigint;
  v_emp text;
begin
  select * into v_p from care_dispatch_proposals where id = p_proposal_id for update;
  if not found then
    return query select false, 'proposal_not_found', null::bigint; return;
  end if;
  if v_p.companion_id <> p_companion_id then
    return query select false, 'not_your_proposal', null::bigint; return;
  end if;
  if v_p.status <> 'proposed' then
    return query select false, 'proposal_not_open', null::bigint; return;
  end if;
  if v_p.expires_at <= now() then
    update care_dispatch_proposals set status = 'expired', updated_at = now()
      where id = p_proposal_id;
    return query select false, 'proposal_expired', null::bigint; return;
  end if;

  -- 僱用條件必須仍然有效
  select employment_type into v_emp from staff_employment_terms
    where companion_id = p_companion_id and status = 'active'
      and effective_from <= current_date
      and (effective_to is null or effective_to >= current_date)
    limit 1;
  if v_emp is null then
    return query select false, 'employment_inactive', null::bigint; return;
  end if;

  -- 鎖住服務列，確認還沒有人被指派
  select companion_id into v_assigned from care_bookings
    where id = v_p.booking_id for update;
  if v_assigned is not null then
    update care_dispatch_proposals set status = 'cancelled', updated_at = now()
      where id = p_proposal_id;
    return query select false, 'already_assigned', null::bigint; return;
  end if;

  -- 正式指派：設定 companion_id 就是既有的 Assignment 語意
  update care_bookings
    set companion_id = p_companion_id, status = '已派工', updated_at = now()
    where id = v_p.booking_id;

  update care_dispatch_proposals
    set status = 'accepted', responded_at = now(), updated_at = now()
    where id = p_proposal_id;

  -- 同一筆服務的其他未回覆邀請一併撤回，讀取範圍立即收回
  update care_dispatch_proposals
    set status = 'cancelled', updated_at = now()
    where booking_id = v_p.booking_id and id <> p_proposal_id and status = 'proposed';

  return query select true, 'ok', v_p.booking_id;
end $$;

-- ── 8. 狀態機守衛 ──────────────────────────────────────────
create or replace function care_guard_proposal() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'proposed' and new.status in ('accepted','declined','expired','cancelled'))
    ) then
      raise exception 'care_dispatch_proposal: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists trg_cdp_guard on care_dispatch_proposals;
create trigger trg_cdp_guard before update on care_dispatch_proposals
  for each row execute function care_guard_proposal();

create or replace function care_guard_time_off() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'submitted' and new.status in ('approved','rejected','cancelled'))
    ) then
      raise exception 'staff_time_off_request: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists trg_sto_guard on staff_time_off_requests;
create trigger trg_sto_guard before update on staff_time_off_requests
  for each row execute function care_guard_time_off();

-- ── 9. updated_at ──────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'staff_employment_terms','staff_capability_verifications','staff_availability_rules',
    'staff_time_off_requests','care_dispatch_proposals'
  ] loop
    execute format('drop trigger if exists trg_%s_touch on %I', t, t);
    execute format(
      'create trigger trg_%s_touch before update on %I for each row execute function care_touch_updated_at()',
      t, t);
  end loop;
end $$;

-- ── 10. Backfill：從既有欄位補資料 ────────────────────────
-- 僱用型態：從 companions.employment_type 帶入。
-- 舊值只有 fulltime / parttime 兩種，對應明確，不是猜測。
-- 若日後出現無法對應的值，會留在 needs_review 由人工補。
insert into staff_employment_terms (companion_id, employment_type, status, effective_from, note)
select c.id,
       case c.employment_type when 'fulltime' then 'full_time' else 'part_time' end,
       case when c.status = 'suspended' then 'paused' else 'active' end,
       coalesce(c.created_at::date, current_date),
       '由 companions.employment_type 自動帶入（Sprint C backfill）'
from companions c
where c.employment_type in ('fulltime', 'parttime')
  and not exists (select 1 from staff_employment_terms t where t.companion_id = c.id);

-- 服務區域：從 companions.service_areas jsonb 展開
insert into staff_service_regions (companion_id, region)
select c.id, r.value #>> '{}'
from companions c, lateral jsonb_array_elements(coalesce(c.service_areas, '[]'::jsonb)) as r(value)
where jsonb_typeof(coalesce(c.service_areas, '[]'::jsonb)) = 'array'
on conflict (companion_id, region) do nothing;

-- ⚠️ 未帶入的情況需要人工處理：
--   select id, name, employment_type from companions
--   where id not in (select companion_id from staff_employment_terms);

-- ── 11. RLS：預設全部拒絕 ─────────────────────────────────
-- 與 Sprint B/D 相同：後台與陪診員端都走 service_role，
-- RLS 是縱深防禦，授權的實際強制點在 Service 層與 Route Handler。
do $$
declare t text;
begin
  foreach t in array array[
    'staff_employment_terms','staff_service_regions','staff_capabilities',
    'staff_capability_verifications','staff_availability_rules',
    'staff_time_off_requests','care_dispatch_proposals'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force row level security', t);
    execute format('revoke all on %I from anon, authenticated', t);
  end loop;
end $$;

-- 完成 ✓


-- ╔═════════════════════════════════════════════════════════╗
-- ║  第 2 段：Sprint D —— 服務履約、家屬交接與結算基礎      ║
-- ╚═════════════════════════════════════════════════════════╝

-- ===========================================================
-- Sprint D：服務履約、家屬資訊交接、異常處理與結算基礎
-- 在 Supabase SQL Editor 執行。可重複執行。
--
-- 服務主體（root）：care_bookings
--   本專案沒有 ServiceOrder / Assignment / ServiceTask 三層模型，
--   實際的正式服務關係就是 care_bookings（含 companion_id 與狀態流）。
--   本檔案所有資料表一律 FK 到 care_bookings，
--   刻意不另建平行的服務關係。
--
-- 與既有 care_booking_events 的分工（重要）：
--   care_booking_events  既有的陪診員工單時間軸，自由文字＋照片，
--                        仍由既有 /companion 工單頁使用，本檔案不修改它。
--   care_service_events  Sprint D 的「受控」事件：型別白名單、append-only、
--                        伺服器寫入時間、家屬可見性分層、更正留痕。
--   兩者 FK 到同一個 booking，不是兩套服務關係。
--   後續 Sprint 應把工單頁遷移到受控事件，屆時再淘汰舊表。
--
-- 這些表都不是醫療紀錄：不存診斷、處方、劑量、治療建議、病歷、
-- 影像、身分證／健保號或任何支付憑證。
-- ===========================================================

-- ── 1. 受控服務事件 ────────────────────────────────────────
create table if not exists care_service_events (
  id              bigint generated by default as identity primary key,
  booking_id      bigint not null references care_bookings(id) on delete restrict,
  companion_id    bigint references companions(id),

  event_type      text not null,
  -- 對家屬可見的簡短訊息，非醫療內容，長度受限
  family_note     text,
  -- internal：只有後台看得到；family：已允許對家屬顯示
  visibility      text not null default 'internal',

  -- 更正留痕：不刪除事件，改以 invalidated 標記並指向更正事件
  invalidated_at        timestamptz,
  invalidated_by_type   text,
  invalidate_reason_code text,
  supersedes_event_id   bigint references care_service_events(id),

  -- 事件時間一律由資料庫寫入，client 不得指定
  occurred_at     timestamptz not null default now(),
  created_at      timestamptz not null default now(),

  constraint care_evt_type_chk check (event_type in (
    'staff_arrived','beneficiary_met','registration_or_checkin_completed',
    'waiting_or_process_in_progress','process_transition',
    'return_arrangement_confirmed','service_handover_ready',
    'requires_supervisor_attention')),
  constraint care_evt_visibility_chk check (visibility in ('internal','family')),
  constraint care_evt_note_len_chk check (family_note is null or char_length(family_note) <= 120),
  constraint care_evt_invalidate_reason_chk check (
    invalidated_at is null or invalidate_reason_code is not null)
);
create index if not exists idx_care_evt_booking on care_service_events(booking_id, occurred_at desc);
create index if not exists idx_care_evt_companion on care_service_events(companion_id);
create index if not exists idx_care_evt_type on care_service_events(event_type);

-- append-only：已建立的事件不可刪除，也不可改寫內容
create or replace function care_guard_service_event() returns trigger
language plpgsql as $$
begin
  if TG_OP = 'DELETE' then
    raise exception 'care_service_events 為 append-only，不可刪除'
      using errcode = 'check_violation';
  end if;
  -- 只允許標記作廢，其餘欄位一律凍結
  if new.booking_id     is distinct from old.booking_id
     or new.companion_id is distinct from old.companion_id
     or new.event_type   is distinct from old.event_type
     or new.family_note  is distinct from old.family_note
     or new.occurred_at  is distinct from old.occurred_at
     or new.created_at   is distinct from old.created_at then
    raise exception 'care_service_events 為 append-only，只能標記作廢，不可改寫內容'
      using errcode = 'check_violation';
  end if;
  if old.invalidated_at is not null and new.invalidated_at is distinct from old.invalidated_at then
    raise exception '事件已作廢，不可重複作廢' using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_evt_guard on care_service_events;
create trigger trg_care_evt_guard before update or delete on care_service_events
  for each row execute function care_guard_service_event();

-- ── 2. 內部服務紀錄（陪診員草稿 → 送審 → 督導核對）────────
create table if not exists care_service_records (
  id                 bigint generated by default as identity primary key,
  booking_id         bigint not null references care_bookings(id) on delete restrict,
  companion_id       bigint not null references companions(id),
  revision           integer not null default 1,

  status             text not null default 'draft',

  -- 結構化的流程完成狀況（客觀事實，不是醫療內容）
  met_completed              boolean not null default false,
  checkin_completed          boolean not null default false,
  process_handover_completed boolean not null default false,
  return_arrangement_completed boolean not null default false,
  family_contact_completed   boolean not null default false,

  family_follow_up_needed    boolean not null default false,
  follow_up_reason_code      text,

  -- 客觀備註。欄位名稱刻意不用 note/diagnosis，避免暗示可寫醫療內容
  objective_summary  text,

  submitted_at       timestamptz,
  reviewed_at        timestamptz,
  reviewed_by_admin_id bigint,
  return_reason_code text,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint care_rec_status_chk check (status in
    ('draft','submitted','returned_for_revision','reviewed','superseded')),
  constraint care_rec_summary_len_chk check (
    objective_summary is null or char_length(objective_summary) <= 500),
  constraint care_rec_followup_chk check (
    family_follow_up_needed = false or follow_up_reason_code is not null),
  constraint care_rec_return_reason_chk check (
    status <> 'returned_for_revision' or return_reason_code is not null),
  constraint care_rec_revision_uniq unique (booking_id, revision)
);
create index if not exists idx_care_rec_booking on care_service_records(booking_id);
create index if not exists idx_care_rec_status on care_service_records(status);
create index if not exists idx_care_rec_companion on care_service_records(companion_id);

-- 一筆服務同時只能有一份「進行中」的紀錄
create unique index if not exists uniq_care_rec_active_per_booking
  on care_service_records(booking_id)
  where status in ('draft','submitted','returned_for_revision');

create or replace function care_guard_service_record() returns trigger
language plpgsql as $$
begin
  -- 已核可的紀錄內容不可被無聲改寫
  if old.status = 'reviewed' then
    if new.objective_summary is distinct from old.objective_summary
       or new.met_completed is distinct from old.met_completed
       or new.checkin_completed is distinct from old.checkin_completed
       or new.process_handover_completed is distinct from old.process_handover_completed
       or new.return_arrangement_completed is distinct from old.return_arrangement_completed
       or new.family_contact_completed is distinct from old.family_contact_completed
       or new.family_follow_up_needed is distinct from old.family_follow_up_needed then
      raise exception '已核可的服務紀錄不可修改內容，請建立新版本'
        using errcode = 'check_violation';
    end if;
  end if;

  -- 送審後陪診員不可再改內容（只有督導退回才能重新編輯）
  if old.status = 'submitted' and new.status = 'submitted' then
    if new.objective_summary is distinct from old.objective_summary then
      raise exception '已送審的服務紀錄不可修改，請先由督導退回'
        using errcode = 'check_violation';
    end if;
  end if;

  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'                 and new.status in ('submitted','superseded')) or
      (old.status = 'submitted'             and new.status in ('reviewed','returned_for_revision')) or
      (old.status = 'returned_for_revision' and new.status in ('submitted','superseded')) or
      (old.status = 'reviewed'              and new.status in ('superseded'))
    ) then
      raise exception 'care_service_record: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_rec_guard on care_service_records;
create trigger trg_care_rec_guard before update on care_service_records
  for each row execute function care_guard_service_record();

-- ── 3. 家屬小結（已審核、可發布／撤回、版本化）─────────────
create table if not exists care_family_summaries (
  id                 bigint generated by default as identity primary key,
  booking_id         bigint not null references care_bookings(id) on delete restrict,
  source_record_id   bigint references care_service_records(id),
  version_number     integer not null default 1,
  status             text not null default 'draft',

  -- 結構化的已發布內容；刻意不用單一自由文字塞整份小結
  service_window_text     text,
  completed_steps_text    text,
  family_actions_text     text,
  next_arrangement_text   text,
  handover_status_text    text,

  published_at       timestamptz,
  published_by_admin_id bigint,
  withdrawn_at       timestamptz,
  withdrawn_by_admin_id bigint,
  withdraw_reason_code text,

  created_by_admin_id bigint,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint care_sum_status_chk check (status in
    ('draft','in_review','published','withdrawn','superseded')),
  constraint care_sum_len_chk check (
    coalesce(char_length(service_window_text),0)   <= 200 and
    coalesce(char_length(completed_steps_text),0)  <= 600 and
    coalesce(char_length(family_actions_text),0)   <= 600 and
    coalesce(char_length(next_arrangement_text),0) <= 400 and
    coalesce(char_length(handover_status_text),0)  <= 300),
  constraint care_sum_withdraw_reason_chk check (
    status <> 'withdrawn' or withdraw_reason_code is not null),
  constraint care_sum_version_uniq unique (booking_id, version_number)
);
create index if not exists idx_care_sum_booking on care_family_summaries(booking_id);
create index if not exists idx_care_sum_status on care_family_summaries(status);

-- 一筆服務同時只能有一份 published 小結
create unique index if not exists uniq_care_sum_published_per_booking
  on care_family_summaries(booking_id) where status = 'published';

create or replace function care_guard_family_summary() returns trigger
language plpgsql as $$
begin
  -- 已發布的內容不可悄悄改寫：要改就撤回或建立新版本
  if old.status = 'published' then
    if new.service_window_text   is distinct from old.service_window_text
       or new.completed_steps_text  is distinct from old.completed_steps_text
       or new.family_actions_text   is distinct from old.family_actions_text
       or new.next_arrangement_text is distinct from old.next_arrangement_text
       or new.handover_status_text  is distinct from old.handover_status_text then
      raise exception '已發布的家屬小結不可修改內容，請撤回或建立新版本'
        using errcode = 'check_violation';
    end if;
  end if;

  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'     and new.status in ('in_review','superseded')) or
      (old.status = 'in_review' and new.status in ('published','draft','superseded')) or
      (old.status = 'published' and new.status in ('withdrawn','superseded')) or
      (old.status = 'withdrawn' and new.status in ('superseded'))
    ) then
      raise exception 'care_family_summary: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_sum_guard on care_family_summaries;
create trigger trg_care_sum_guard before update on care_family_summaries
  for each row execute function care_guard_family_summary();

-- ── 4. 異常事件（營運升級，非醫療分級、非急救）─────────────
create table if not exists care_incidents (
  id              bigint generated by default as identity primary key,
  booking_id      bigint not null references care_bookings(id) on delete restrict,
  companion_id    bigint references companions(id),
  related_event_id bigint references care_service_events(id),

  incident_type   text not null,
  severity        text not null default 'low',   -- 營運優先級，不是醫療嚴重度
  status          text not null default 'open',
  description     text,

  notification_status text not null default 'not_required',

  acknowledged_at   timestamptz,
  acknowledged_by_admin_id bigint,
  resolved_at       timestamptz,
  resolved_by_admin_id bigint,
  resolution_code   text,
  closed_at         timestamptz,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint care_inc_type_chk check (incident_type in (
    'family_contact_needed','schedule_or_handover_issue',
    'facility_process_follow_up','supervisor_attention_needed')),
  constraint care_inc_severity_chk check (severity in ('low','medium','high')),
  constraint care_inc_status_chk check (status in ('open','acknowledged','resolved','closed')),
  constraint care_inc_notif_chk check (notification_status in
    ('not_required','pending','prepared','sent_or_confirmed','failed')),
  constraint care_inc_desc_len_chk check (description is null or char_length(description) <= 300),
  constraint care_inc_resolution_chk check (
    status not in ('resolved','closed') or resolution_code is not null)
);
create index if not exists idx_care_inc_booking on care_incidents(booking_id);
create index if not exists idx_care_inc_status on care_incidents(status);
create index if not exists idx_care_inc_notif on care_incidents(notification_status);

create or replace function care_guard_incident() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'open'         and new.status in ('acknowledged','resolved')) or
      (old.status = 'acknowledged' and new.status in ('resolved')) or
      (old.status = 'resolved'     and new.status in ('closed'))
    ) then
      raise exception 'care_incident: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;

  -- 目前沒有正式的外部通知 provider：資料庫層直接擋下「已送出」
  -- 避免任何程式路徑產生假的已通知狀態。
  -- 未來接上 connector 時，改為由該 connector 的受控函式寫入。
  if new.notification_status = 'sent_or_confirmed'
     and old.notification_status is distinct from 'sent_or_confirmed' then
    raise exception '目前沒有正式通知管道，不可標記為已送出'
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_inc_guard on care_incidents;
create trigger trg_care_inc_guard before update on care_incidents
  for each row execute function care_guard_incident();

-- ── 5. 單筆服務的家屬授權（預設全部拒絕）───────────────────
-- 付款人／預約人／聯絡人都不會因為身分自動取得閱覽權，
-- 必須有一筆有效、未撤回的授權列。
create table if not exists care_service_authorizations (
  id            bigint generated by default as identity primary key,
  booking_id    bigint not null references care_bookings(id) on delete restrict,
  -- 對應 Supabase Auth 的會員；沒有帳號就無法被授權
  user_id       uuid not null,
  scope         text not null,

  granted_at    timestamptz not null default now(),
  granted_by_admin_id bigint,
  revoked_at    timestamptz,
  revoked_by_admin_id bigint,
  revoke_reason_code text,

  constraint care_auth_scope_chk check (scope in
    ('receive_service_notification','view_service_summary','view_service_photo')),
  constraint care_auth_uniq unique (booking_id, user_id, scope)
);
create index if not exists idx_care_auth_lookup
  on care_service_authorizations(user_id, booking_id) where revoked_at is null;

-- view_service_photo 本輪一律不啟用：資料庫層直接擋
create or replace function care_guard_authorization() returns trigger
language plpgsql as $$
begin
  if new.scope = 'view_service_photo' and new.revoked_at is null then
    raise exception '照片檢視權限本輪未啟用，需先完成法律、同意與私有儲存設計'
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists trg_care_auth_guard on care_service_authorizations;
create trigger trg_care_auth_guard before insert or update on care_service_authorizations
  for each row execute function care_guard_authorization();

-- ── 6. 結算基礎（兼職）─────────────────────────────────────
-- ⚠️ 這裡「不」動既有的 care_bookings 結算欄位與 /admin/settlement。
-- 那套仍是目前實際在用的系統。本區是 Sprint D 要求的可稽核 line/batch
-- 基礎，為附加而非取代；是否整併為單一系統是後續的營運決定。
-- 兩套都不會自動付款，也不產生任何付款成功資訊。
create table if not exists care_settlement_batches (
  id             bigint generated by default as identity primary key,
  batch_no       text not null unique,
  period_start   date not null,
  period_end     date not null,
  status         text not null default 'draft',
  created_by_admin_id  bigint,
  approved_by_admin_id bigint,
  approved_at    timestamptz,
  published_at   timestamptz,
  closed_at      timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint care_batch_status_chk check (status in ('draft','approved','published','closed')),
  constraint care_batch_period_chk check (period_end >= period_start)
);
create index if not exists idx_care_batch_status on care_settlement_batches(status);

create table if not exists care_settlement_lines (
  id             bigint generated by default as identity primary key,
  booking_id     bigint not null references care_bookings(id) on delete restrict,
  companion_id   bigint not null references companions(id),
  batch_id       bigint references care_settlement_batches(id),

  employment_type_snapshot text not null,
  line_type      text not null,
  amount         integer not null,
  currency       text not null default 'TWD',
  -- 金額怎麼來的：快照計算依據，便於日後對帳
  basis_snapshot text not null,
  reason_code    text,

  status         text not null default 'pending_review',
  reviewed_by_admin_id bigint,
  reviewed_at    timestamptz,
  review_note    text,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint care_line_type_chk check (line_type in
    ('service_compensation','transport_reimbursement','manual_adjustment')),
  constraint care_line_status_chk check (status in
    ('pending_review','approved','rejected','published_to_staff','batched')),
  constraint care_line_employment_chk check (employment_type_snapshot in ('fulltime','parttime')),
  constraint care_line_currency_chk check (currency = 'TWD'),
  constraint care_line_amount_chk check (amount >= 0),
  constraint care_line_basis_len_chk check (char_length(basis_snapshot) between 1 and 200),
  constraint care_line_note_len_chk check (review_note is null or char_length(review_note) <= 200),
  -- 同一服務同一類型只能有一筆，避免重試或並發造成重複計算
  constraint care_line_uniq unique (booking_id, line_type)
);
create index if not exists idx_care_line_companion on care_settlement_lines(companion_id, status);
create index if not exists idx_care_line_batch on care_settlement_lines(batch_id);
create index if not exists idx_care_line_status on care_settlement_lines(status);

create or replace function care_guard_settlement_line() returns trigger
language plpgsql as $$
begin
  -- 全職不在本輪產生報酬 line
  if new.employment_type_snapshot = 'fulltime' then
    raise exception '全職陪診員本輪不產生結算 line，只提供服務統計'
      using errcode = 'check_violation';
  end if;

  if TG_OP = 'UPDATE' then
    -- 已發布給陪診員或已入批次的金額不可再改
    if old.status in ('published_to_staff','batched')
       and (new.amount is distinct from old.amount
            or new.line_type is distinct from old.line_type
            or new.basis_snapshot is distinct from old.basis_snapshot) then
      raise exception '已發布或已入批次的結算明細不可修改金額'
        using errcode = 'check_violation';
    end if;

    if new.status is distinct from old.status then
      if not (
        (old.status = 'pending_review'     and new.status in ('approved','rejected')) or
        (old.status = 'approved'           and new.status in ('batched','published_to_staff','pending_review')) or
        (old.status = 'batched'            and new.status in ('published_to_staff')) or
        (old.status = 'rejected'           and new.status in ('pending_review'))
      ) then
        raise exception 'care_settlement_line: 不允許的狀態轉換 % -> %', old.status, new.status
          using errcode = 'check_violation';
      end if;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_line_guard on care_settlement_lines;
create trigger trg_care_line_guard before insert or update on care_settlement_lines
  for each row execute function care_guard_settlement_line();

create or replace function care_guard_settlement_batch() returns trigger
language plpgsql as $$
begin
  if new.status is distinct from old.status then
    if not (
      (old.status = 'draft'     and new.status in ('approved')) or
      (old.status = 'approved'  and new.status in ('published','draft')) or
      (old.status = 'published' and new.status in ('closed'))
    ) then
      raise exception 'care_settlement_batch: 不允許的狀態轉換 % -> %', old.status, new.status
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_care_batch_guard on care_settlement_batches;
create trigger trg_care_batch_guard before update on care_settlement_batches
  for each row execute function care_guard_settlement_batch();

-- ── 7. updated_at ──────────────────────────────────────────
drop trigger if exists trg_care_rec_touch on care_service_records;
create trigger trg_care_rec_touch before update on care_service_records
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_sum_touch on care_family_summaries;
create trigger trg_care_sum_touch before update on care_family_summaries
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_inc_touch on care_incidents;
create trigger trg_care_inc_touch before update on care_incidents
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_line_touch on care_settlement_lines;
create trigger trg_care_line_touch before update on care_settlement_lines
  for each row execute function care_touch_updated_at();

drop trigger if exists trg_care_batch_touch on care_settlement_batches;
create trigger trg_care_batch_touch before update on care_settlement_batches
  for each row execute function care_touch_updated_at();

-- ── 8. RLS：預設全部拒絕 ───────────────────────────────────
-- 與 Sprint B 相同：後台／陪診員端／家屬端 API 都走 service_role，
-- 因此 RLS 是縱深防禦（擋 anon key 與 authenticated 直連），
-- 授權的實際強制點在 Service 層與 Route Handler。詳見 SECURITY.md。
do $$
declare t text;
begin
  foreach t in array array[
    'care_service_events','care_service_records','care_family_summaries',
    'care_incidents','care_service_authorizations',
    'care_settlement_lines','care_settlement_batches'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force row level security', t);
    execute format('revoke all on %I from anon, authenticated', t);
  end loop;
end $$;

-- 完成 ✓
