// 後台可指派的權限清單（'all' = 超級管理員，擁有全部權限，單獨處理）
export const PERMISSION_CATALOG: { key: string; label: string; hint?: string }[] = [
  { key: 'orders.view', label: '查看訂單、銷售報表、復購分析', hint: '含客戶手機等資料' },
  { key: 'orders.status', label: '更新訂單狀態' },
  { key: 'orders.status.ship', label: '出貨作業（備貨 / 出貨 / 到店）' },
  { key: 'orders.edit', label: '編輯訂單' },
  { key: 'products.all', label: '商品管理、健康知識文章' },
  { key: 'categories.all', label: '健康分類管理' },
  { key: 'events.view', label: '社群活動報名管理' },
  // ── 陪診營運（Sprint B）──────────────────────────────────
  // 這四個與既有的 care.view（陪診預約頁）責任不同，不可互相沿用。
  { key: 'care_operations.view', label: '陪診營運：檢視總覽與清單', hint: '不含補充需求等自由文字' },
  { key: 'care_intake.manage', label: '陪診營運：初評審查', hint: '可看到補充需求與聯絡方式' },
  { key: 'care_quote.manage', label: '陪診營運：報價草稿與確認' },
  { key: 'care_case.manage', label: '陪診營運：案件狀態與人工收款確認' },
  // ── 陪診履約（Sprint D）──────────────────────────────────
  { key: 'care_record.review', label: '陪診履約：服務紀錄核對', hint: '可看到陪診員的內部客觀紀錄' },
  { key: 'care_summary.review', label: '陪診履約：家屬小結審核與發布', hint: '唯一能對家屬發布內容的權限' },
  { key: 'care_incident.manage', label: '陪診履約：異常事件處理與通知決策' },
  { key: 'care_settlement.manage', label: '陪診履約：結算明細與批次', hint: '唯一能看到報酬金額的權限' },
  // ── 陪診人力與媒合（Sprint C）────────────────────────────
  { key: 'care_staff.manage', label: '陪診人力：名冊、僱用型態、服務區域' },
  { key: 'care_staff_credential.manage', label: '陪診人力：能力驗證', hint: '陪診員不能自行標記為已驗證' },
  { key: 'care_schedule.manage', label: '陪診人力：班表與可服務時段檢視' },
  { key: 'care_staff_time_off.review', label: '陪診人力：請假／暫停接案審核' },
  { key: 'care_dispatch.manage', label: '陪診人力：人工媒合與兼職邀請' },
  // ── 營運閉環（Sprint E）────────────────────────────────
  { key: 'care_notification.manage', label: '陪診營運：站內通知與 outbox', hint: '外部通知尚未啟用，只看得到狀態' },
  { key: 'care_feedback.manage', label: '陪診營運：家屬回饋處理' },
  { key: 'care_concern.manage', label: '陪診營運：意見／申訴處理' },
  { key: 'care_quality.review', label: '陪診品質：服務品質覆核' },
  { key: 'care_quality.manage', label: '陪診品質：改善事項指派與覆核' },
  { key: 'care_insights.view', label: '陪診營運：去識別化營運指標' },
  { key: 'care_release_readiness.view', label: '陪診營運：上線檢核' },
  { key: 'care_policy.manage', label: '陪診營運：條款與隱私版本管理', hint: '正文需由法務確認後填入' },
  { key: 'care_data_lifecycle.manage', label: '陪診營運：資料保留待辦清單', hint: '本輪不刪除任何資料' },
]

export const ALL_PERMISSION = 'all'

// 稽核動作標籤
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  page_view: '瀏覽頁面',
  export_customers: '下載客戶 / 復購名單',
  export_event_registrations: '下載活動報名名單',
  export_orders: '下載訂單資料',
  export_members: '下載會員資料',
  // 陪診營運（Sprint B）
  'care_intake.review_start': '陪診初評：開始審查',
  'care_intake.request_more_info': '陪診初評：要求補充資料',
  'care_intake.decline': '陪診初評：婉拒',
  'care_intake.convert_to_case': '陪診初評：轉為案件',
  'care_case.cancel': '陪診案件：取消',
  'care_case.mark_payment_received': '陪診案件：人工確認收款',
  'care_quote.draft_create': '陪診報價：建立草稿',
  'care_quote.update_draft': '陪診報價：修改草稿',
  'care_quote.send': '陪診報價：發送',
  'care_quote.confirm': '陪診報價：確認',
  'care_quote.expire': '陪診報價：設為過期',
  'care_quote.cancel': '陪診報價：作廢',
  // 陪診履約（Sprint D）
  'care_event.visibility': '陪診事件：調整家屬可見性',
  'care_record.review': '陪診紀錄：核可',
  'care_record.return': '陪診紀錄：退回補正',
  'care_summary.draft_create': '家屬小結：建立草稿',
  'care_summary.update_draft': '家屬小結：修改草稿',
  'care_summary.submit': '家屬小結：送審',
  'care_summary.publish': '家屬小結：發布',
  'care_summary.withdraw': '家屬小結：撤回',
  'care_incident.acknowledge': '異常事件：受理',
  'care_incident.resolve': '異常事件：處理完成',
  'care_incident.close': '異常事件：結案',
  'care_incident.notification': '異常事件：通知狀態',
  'care_authorization.grant': '家屬授權：開通',
  'care_authorization.revoke': '家屬授權：撤回',
  'care_settlement.line_generate': '結算明細：產生',
  'care_settlement.line_manual': '結算明細：人工新增',
  'care_settlement.line_review': '結算明細：審核',
  'care_settlement.batch_create': '結算批次：建立',
  'care_settlement.batch_approve': '結算批次：核准',
  'care_settlement.batch_publish': '結算批次：發布',
  'care_settlement.batch_close': '結算批次：關閉',
  // 陪診人力與媒合（Sprint C）
  'care_staff.employment_create': '陪診人力：建立僱用條件',
  'care_staff.employment_end': '陪診人力：結束僱用條件',
  'care_staff.employment_pause': '陪診人力：暫停接案',
  'care_staff.employment_resume': '陪診人力：恢復接案',
  'care_staff.region_add': '陪診人力：新增服務區域',
  'care_staff.region_remove': '陪診人力：移除服務區域',
  'care_staff.capability_verify': '陪診人力：能力驗證通過',
  'care_staff.capability_expire': '陪診人力：能力驗證過期',
  'care_staff.capability_suspend': '陪診人力：能力驗證暫停',
  'care_time_off.review': '陪診人力：請假審核',
  'care_dispatch.materialize': '媒合：案件轉為正式服務',
  'care_dispatch.assign_full_time': '媒合：全職正式指派',
  'care_dispatch.proposal_create': '媒合：建立兼職邀請',
  'care_dispatch.proposal_cancel': '媒合：撤回邀請',
  'care_dispatch.proposal_expire': '媒合：邀請逾時',

  // 營運閉環（Sprint E）
  'care_notification.outbox_suppress': '通知：抑制外部發送',
  'care_feedback.request_create': '回饋：建立邀請',
  'care_feedback.review_start': '回饋：開始處理',
  'care_feedback.close': '回饋：結案',
  'care_concern.create': '意見案件：建立',
  'care_concern.acknowledge': '意見案件：受理',
  'care_concern.assign': '意見案件：指派負責人',
  'care_concern.resolve': '意見案件：標記已處理',
  'care_concern.close': '意見案件：結案',
  'care_quality.review_create': '品質：建立覆核',
  'care_quality.review_start': '品質：開始覆核',
  'care_quality.review_complete': '品質：完成覆核',
  'care_quality.follow_up_create': '品質：建立改善事項',
  'care_quality.follow_up_complete': '品質：改善事項完成',
  'care_quality.follow_up_verify': '品質：改善事項覆核通過',
  'care_policy.draft_create': '政策：建立版本草稿',
  'care_policy.publish': '政策：發布版本',
  'care_data_lifecycle.create': '資料保留：建立待辦',
  'care_data_lifecycle.mark_reviewed': '資料保留：標記已檢視',
}

// 屬於「資料下載」的動作（需提示超級管理員）
export function isDownloadAction(action: string): boolean {
  return action.startsWith('export_')
}
